# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\post\addPostWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addPostWidget(object):
    def setupUi(self, addPostWidget):
        addPostWidget.setObjectName("addPostWidget")
        addPostWidget.resize(442, 301)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        addPostWidget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\post\\../../images/newPost.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addPostWidget.setWindowIcon(icon)
        addPostWidget.setStyleSheet("QWidget\n"
"{\n"
"    background: rgb(30, 30, 30);\n"
"    color: white;\n"
"\n"
"}\n"
"")
        self.rectangle = QtWidgets.QFrame(addPostWidget)
        self.rectangle.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.rectangle.setStyleSheet("border:0px;\n"
"background-color: rgb(180, 0, 0);\n"
"border: 1px solid rgb(180, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.labelComplect = QtWidgets.QLabel(addPostWidget)
        self.labelComplect.setGeometry(QtCore.QRect(180, 30, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        self.labelComplect.setFont(font)
        self.labelComplect.setStyleSheet("border:0px;")
        self.labelComplect.setAlignment(QtCore.Qt.AlignCenter)
        self.labelComplect.setObjectName("labelComplect")
        self.line = QtWidgets.QFrame(addPostWidget)
        self.line.setGeometry(QtCore.QRect(20, 60, 411, 16))
        self.line.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(180, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbFullName = QtWidgets.QLabel(addPostWidget)
        self.lbFullName.setGeometry(QtCore.QRect(120, 100, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbFullName.setFont(font)
        self.lbFullName.setStyleSheet("border:0px;")
        self.lbFullName.setObjectName("lbFullName")
        self.btnPostCancel = QtWidgets.QPushButton(addPostWidget)
        self.btnPostCancel.setGeometry(QtCore.QRect(240, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnPostCancel.setFont(font)
        self.btnPostCancel.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnPostCancel.setAutoDefault(False)
        self.btnPostCancel.setDefault(False)
        self.btnPostCancel.setFlat(False)
        self.btnPostCancel.setObjectName("btnPostCancel")
        self.btnPostSave = QtWidgets.QPushButton(addPostWidget)
        self.btnPostSave.setGeometry(QtCore.QRect(70, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnPostSave.setFont(font)
        self.btnPostSave.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-bottom: 1px solid rgb(0, 255, 8);\n"
"}\n"
"")
        self.btnPostSave.setObjectName("btnPostSave")
        self.line_2 = QtWidgets.QFrame(addPostWidget)
        self.line_2.setGeometry(QtCore.QRect(20, 210, 411, 16))
        self.line_2.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(180, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lePostName = QtWidgets.QLineEdit(addPostWidget)
        self.lePostName.setGeometry(QtCore.QRect(120, 130, 191, 31))
        self.lePostName.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.lePostName.setObjectName("lePostName")

        self.retranslateUi(addPostWidget)
        self.btnPostCancel.clicked.connect(addPostWidget.close)
        QtCore.QMetaObject.connectSlotsByName(addPostWidget)

    def retranslateUi(self, addPostWidget):
        _translate = QtCore.QCoreApplication.translate
        addPostWidget.setWindowTitle(_translate("addPostWidget", "Добавить поставщика"))
        self.labelComplect.setText(_translate("addPostWidget", "Поставщик [комплектующее]"))
        self.lbFullName.setText(_translate("addPostWidget", "Наименование поставщика"))
        self.btnPostCancel.setText(_translate("addPostWidget", "Отмена"))
        self.btnPostSave.setText(_translate("addPostWidget", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addPostWidget = QtWidgets.QWidget()
    ui = Ui_addPostWidget()
    ui.setupUi(addPostWidget)
    addPostWidget.show()
    sys.exit(app.exec_())
