# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\filter\widgetCoolFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetCoolFilter(object):
    def setupUi(self, WidgetCoolFilter):
        WidgetCoolFilter.setObjectName("WidgetCoolFilter")
        WidgetCoolFilter.resize(365, 685)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/filters.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WidgetCoolFilter.setWindowIcon(icon)
        WidgetCoolFilter.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(30,30,30);\n"
"    color: white;\n"
"\n"
"}\n"
"")
        self.btnAccept = QtWidgets.QPushButton(WidgetCoolFilter)
        self.btnAccept.setGeometry(QtCore.QRect(60, 640, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnAccept.setFont(font)
        self.btnAccept.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"}\n"
"")
        self.btnAccept.setObjectName("btnAccept")
        self.btnClose = QtWidgets.QPushButton(WidgetCoolFilter)
        self.btnClose.setGeometry(QtCore.QRect(190, 640, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnClose.setObjectName("btnClose")
        self.rectangle = QtWidgets.QFrame(WidgetCoolFilter)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.btnResetAll = QtWidgets.QPushButton(WidgetCoolFilter)
        self.btnResetAll.setGeometry(QtCore.QRect(250, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetAll.setFont(font)
        self.btnResetAll.setStyleSheet("QPushButton\n"
"{\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetAll.setObjectName("btnResetAll")
        self.toolBoxCoolFilter = QtWidgets.QToolBox(WidgetCoolFilter)
        self.toolBoxCoolFilter.setGeometry(QtCore.QRect(30, 90, 311, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxCoolFilter.sizePolicy().hasHeightForWidth())
        self.toolBoxCoolFilter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.toolBoxCoolFilter.setFont(font)
        self.toolBoxCoolFilter.setAccessibleName("")
        self.toolBoxCoolFilter.setStyleSheet("QToolBox\n"
"{\n"
"    background: rgb(30, 30, 30);\n"
"    border: 1px solid red;\n"
"    margin: 1px;\n"
"    icon-size: 23px;\n"
"}\n"
"\n"
"QToolBox::tab\n"
"{\n"
"    height:250px;\n"
"    background: rgb(30, 30, 30);\n"
"    margin-left: 1px;\n"
"    left: -1px;\n"
"    color: rgb(235, 235, 235);\n"
"    border-top: 1px solid;\n"
"    border-bottom: 3px solid;\n"
"}\n"
"\n"
"QToolBox::tab:selected\n"
"{\n"
"    background-color: rgb(45, 45, 45);\n"
"    border-bottom: 2px solid  rgb(180, 0, 0);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBox::tab:hover\n"
"{\n"
"    background-color: rgb(65, 65, 65);\n"
"    border-bottom: 5px solid;\n"
"    border-color: black;\n"
"}\n"
"")
        self.toolBoxCoolFilter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBoxCoolFilter.setLineWidth(0)
        self.toolBoxCoolFilter.setMidLineWidth(1)
        self.toolBoxCoolFilter.setObjectName("toolBoxCoolFilter")
        self.price = QtWidgets.QWidget()
        self.price.setGeometry(QtCore.QRect(0, 0, 307, 194))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.price.setSizeIncrement(QtCore.QSize(0, 0))
        self.price.setBaseSize(QtCore.QSize(0, 200))
        self.price.setObjectName("price")
        self.tbFrameProc = QtWidgets.QFrame(self.price)
        self.tbFrameProc.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.tbFrameProc.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}")
        self.tbFrameProc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbFrameProc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbFrameProc.setObjectName("tbFrameProc")
        self.sliderPriceMin = QtWidgets.QSlider(self.tbFrameProc)
        self.sliderPriceMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderPriceMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderPriceMin.setProperty("value", 0)
        self.sliderPriceMin.setTracking(True)
        self.sliderPriceMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPriceMin.setInvertedAppearance(False)
        self.sliderPriceMin.setInvertedControls(False)
        self.sliderPriceMin.setObjectName("sliderPriceMin")
        self.line_2 = QtWidgets.QFrame(self.tbFrameProc)
        self.line_2.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_2.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.sliderPriceMax = QtWidgets.QSlider(self.tbFrameProc)
        self.sliderPriceMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderPriceMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderPriceMax.setProperty("value", 0)
        self.sliderPriceMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPriceMax.setInvertedAppearance(False)
        self.sliderPriceMax.setInvertedControls(False)
        self.sliderPriceMax.setObjectName("sliderPriceMax")
        self.btnResetPrice = QtWidgets.QPushButton(self.tbFrameProc)
        self.btnResetPrice.setGeometry(QtCore.QRect(220, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetPrice.setFont(font)
        self.btnResetPrice.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetPrice.setObjectName("btnResetPrice")
        self.lbMinPrice = QtWidgets.QLabel(self.tbFrameProc)
        self.lbMinPrice.setGeometry(QtCore.QRect(10, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinPrice.setFont(font)
        self.lbMinPrice.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinPrice.setObjectName("lbMinPrice")
        self.lbMaxPrice = QtWidgets.QLabel(self.tbFrameProc)
        self.lbMaxPrice.setGeometry(QtCore.QRect(180, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxPrice.setFont(font)
        self.lbMaxPrice.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxPrice.setObjectName("lbMaxPrice")
        self.leMinPrice = QtWidgets.QLineEdit(self.tbFrameProc)
        self.leMinPrice.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinPrice.setFont(font)
        self.leMinPrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinPrice.setObjectName("leMinPrice")
        self.leMaxPrice = QtWidgets.QLineEdit(self.tbFrameProc)
        self.leMaxPrice.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxPrice.setFont(font)
        self.leMaxPrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxPrice.setObjectName("leMaxPrice")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.toolBoxCoolFilter.addItem(self.price, icon1, "")
        self.proizvoditel = QtWidgets.QWidget()
        self.proizvoditel.setGeometry(QtCore.QRect(0, 0, 307, 194))
        self.proizvoditel.setObjectName("proizvoditel")
        self.frameProizv = QtWidgets.QFrame(self.proizvoditel)
        self.frameProizv.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameProizv.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameProizv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProizv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProizv.setObjectName("frameProizv")
        self.tableProizv = QtWidgets.QTableWidget(self.frameProizv)
        self.tableProizv.setEnabled(True)
        self.tableProizv.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableProizv.setFont(font)
        self.tableProizv.setMouseTracking(True)
        self.tableProizv.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableProizv.setAutoFillBackground(False)
        self.tableProizv.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableProizv.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableProizv.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableProizv.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProizv.setShowGrid(False)
        self.tableProizv.setGridStyle(QtCore.Qt.SolidLine)
        self.tableProizv.setObjectName("tableProizv")
        self.tableProizv.setColumnCount(2)
        self.tableProizv.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProizv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProizv.setHorizontalHeaderItem(1, item)
        self.tableProizv.horizontalHeader().setVisible(False)
        self.tableProizv.horizontalHeader().setCascadingSectionResizes(True)
        self.tableProizv.horizontalHeader().setDefaultSectionSize(120)
        self.tableProizv.horizontalHeader().setHighlightSections(False)
        self.tableProizv.horizontalHeader().setMinimumSectionSize(15)
        self.tableProizv.horizontalHeader().setSortIndicatorShown(True)
        self.tableProizv.horizontalHeader().setStretchLastSection(False)
        self.tableProizv.verticalHeader().setVisible(False)
        self.tableProizv.verticalHeader().setCascadingSectionResizes(False)
        self.tableProizv.verticalHeader().setMinimumSectionSize(10)
        self.btnResetProizv = QtWidgets.QPushButton(self.frameProizv)
        self.btnResetProizv.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetProizv.setFont(font)
        self.btnResetProizv.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetProizv.setObjectName("btnResetProizv")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/up-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.toolBoxCoolFilter.addItem(self.proizvoditel, icon2, "")
        self.construction = QtWidgets.QWidget()
        self.construction.setGeometry(QtCore.QRect(0, 0, 307, 194))
        self.construction.setObjectName("construction")
        self.frameConstr = QtWidgets.QFrame(self.construction)
        self.frameConstr.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameConstr.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameConstr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameConstr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameConstr.setObjectName("frameConstr")
        self.tableConstr = QtWidgets.QTableWidget(self.frameConstr)
        self.tableConstr.setEnabled(True)
        self.tableConstr.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableConstr.setFont(font)
        self.tableConstr.setMouseTracking(True)
        self.tableConstr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableConstr.setAutoFillBackground(False)
        self.tableConstr.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableConstr.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableConstr.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableConstr.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableConstr.setShowGrid(False)
        self.tableConstr.setGridStyle(QtCore.Qt.SolidLine)
        self.tableConstr.setObjectName("tableConstr")
        self.tableConstr.setColumnCount(2)
        self.tableConstr.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableConstr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableConstr.setHorizontalHeaderItem(1, item)
        self.tableConstr.horizontalHeader().setVisible(False)
        self.tableConstr.horizontalHeader().setCascadingSectionResizes(True)
        self.tableConstr.horizontalHeader().setDefaultSectionSize(120)
        self.tableConstr.horizontalHeader().setHighlightSections(False)
        self.tableConstr.horizontalHeader().setMinimumSectionSize(15)
        self.tableConstr.horizontalHeader().setSortIndicatorShown(True)
        self.tableConstr.horizontalHeader().setStretchLastSection(False)
        self.tableConstr.verticalHeader().setVisible(False)
        self.tableConstr.verticalHeader().setCascadingSectionResizes(False)
        self.tableConstr.verticalHeader().setMinimumSectionSize(10)
        self.btnResetConstr = QtWidgets.QPushButton(self.frameConstr)
        self.btnResetConstr.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetConstr.setFont(font)
        self.btnResetConstr.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetConstr.setObjectName("btnResetConstr")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBoxCoolFilter.addItem(self.construction, icon3, "")
        self.socket = QtWidgets.QWidget()
        self.socket.setGeometry(QtCore.QRect(0, 0, 307, 194))
        self.socket.setObjectName("socket")
        self.frameSocket = QtWidgets.QFrame(self.socket)
        self.frameSocket.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameSocket.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameSocket.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSocket.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSocket.setObjectName("frameSocket")
        self.tableSocket = QtWidgets.QTableWidget(self.frameSocket)
        self.tableSocket.setEnabled(True)
        self.tableSocket.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableSocket.setFont(font)
        self.tableSocket.setMouseTracking(True)
        self.tableSocket.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableSocket.setAutoFillBackground(False)
        self.tableSocket.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableSocket.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableSocket.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableSocket.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableSocket.setShowGrid(False)
        self.tableSocket.setGridStyle(QtCore.Qt.SolidLine)
        self.tableSocket.setObjectName("tableSocket")
        self.tableSocket.setColumnCount(2)
        self.tableSocket.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSocket.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSocket.setHorizontalHeaderItem(1, item)
        self.tableSocket.horizontalHeader().setVisible(False)
        self.tableSocket.horizontalHeader().setCascadingSectionResizes(True)
        self.tableSocket.horizontalHeader().setDefaultSectionSize(120)
        self.tableSocket.horizontalHeader().setHighlightSections(False)
        self.tableSocket.horizontalHeader().setMinimumSectionSize(15)
        self.tableSocket.horizontalHeader().setSortIndicatorShown(True)
        self.tableSocket.horizontalHeader().setStretchLastSection(False)
        self.tableSocket.verticalHeader().setVisible(False)
        self.tableSocket.verticalHeader().setCascadingSectionResizes(False)
        self.tableSocket.verticalHeader().setMinimumSectionSize(10)
        self.btnResetSocket = QtWidgets.QPushButton(self.frameSocket)
        self.btnResetSocket.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetSocket.setFont(font)
        self.btnResetSocket.setStyleSheet("QPushButton\n"
"{    \n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetSocket.setObjectName("btnResetSocket")
        self.toolBoxCoolFilter.addItem(self.socket, icon3, "")
        self.type = QtWidgets.QWidget()
        self.type.setGeometry(QtCore.QRect(0, 0, 307, 194))
        self.type.setObjectName("type")
        self.frameType = QtWidgets.QFrame(self.type)
        self.frameType.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameType.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameType.setObjectName("frameType")
        self.tableType = QtWidgets.QTableWidget(self.frameType)
        self.tableType.setEnabled(True)
        self.tableType.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableType.setFont(font)
        self.tableType.setMouseTracking(True)
        self.tableType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableType.setAutoFillBackground(False)
        self.tableType.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableType.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableType.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableType.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableType.setShowGrid(False)
        self.tableType.setGridStyle(QtCore.Qt.SolidLine)
        self.tableType.setObjectName("tableType")
        self.tableType.setColumnCount(2)
        self.tableType.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableType.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableType.setHorizontalHeaderItem(1, item)
        self.tableType.horizontalHeader().setVisible(False)
        self.tableType.horizontalHeader().setCascadingSectionResizes(True)
        self.tableType.horizontalHeader().setDefaultSectionSize(120)
        self.tableType.horizontalHeader().setHighlightSections(False)
        self.tableType.horizontalHeader().setMinimumSectionSize(15)
        self.tableType.horizontalHeader().setSortIndicatorShown(True)
        self.tableType.horizontalHeader().setStretchLastSection(False)
        self.tableType.verticalHeader().setVisible(False)
        self.tableType.verticalHeader().setCascadingSectionResizes(False)
        self.tableType.verticalHeader().setMinimumSectionSize(10)
        self.btnResetType = QtWidgets.QPushButton(self.frameType)
        self.btnResetType.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetType.setFont(font)
        self.btnResetType.setStyleSheet("QPushButton\n"
"{    \n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetType.setObjectName("btnResetType")
        self.toolBoxCoolFilter.addItem(self.type, icon3, "")
        self.heatpipe = QtWidgets.QWidget()
        self.heatpipe.setGeometry(QtCore.QRect(0, 0, 307, 194))
        self.heatpipe.setObjectName("heatpipe")
        self.framePipe = QtWidgets.QFrame(self.heatpipe)
        self.framePipe.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.framePipe.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.framePipe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePipe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePipe.setObjectName("framePipe")
        self.tablePipe = QtWidgets.QTableWidget(self.framePipe)
        self.tablePipe.setEnabled(True)
        self.tablePipe.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tablePipe.setFont(font)
        self.tablePipe.setMouseTracking(True)
        self.tablePipe.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tablePipe.setAutoFillBackground(False)
        self.tablePipe.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tablePipe.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tablePipe.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tablePipe.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablePipe.setShowGrid(False)
        self.tablePipe.setGridStyle(QtCore.Qt.SolidLine)
        self.tablePipe.setObjectName("tablePipe")
        self.tablePipe.setColumnCount(2)
        self.tablePipe.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePipe.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePipe.setHorizontalHeaderItem(1, item)
        self.tablePipe.horizontalHeader().setVisible(False)
        self.tablePipe.horizontalHeader().setCascadingSectionResizes(True)
        self.tablePipe.horizontalHeader().setDefaultSectionSize(120)
        self.tablePipe.horizontalHeader().setHighlightSections(False)
        self.tablePipe.horizontalHeader().setMinimumSectionSize(15)
        self.tablePipe.horizontalHeader().setSortIndicatorShown(True)
        self.tablePipe.horizontalHeader().setStretchLastSection(False)
        self.tablePipe.verticalHeader().setVisible(False)
        self.tablePipe.verticalHeader().setCascadingSectionResizes(False)
        self.tablePipe.verticalHeader().setMinimumSectionSize(10)
        self.btnResetPipe = QtWidgets.QPushButton(self.framePipe)
        self.btnResetPipe.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetPipe.setFont(font)
        self.btnResetPipe.setStyleSheet("QPushButton\n"
"{\n"
"\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetPipe.setObjectName("btnResetPipe")
        self.toolBoxCoolFilter.addItem(self.heatpipe, icon3, "")
        self.pinCool = QtWidgets.QWidget()
        self.pinCool.setGeometry(QtCore.QRect(0, 0, 307, 194))
        self.pinCool.setObjectName("pinCool")
        self.framePinCool = QtWidgets.QFrame(self.pinCool)
        self.framePinCool.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.framePinCool.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.framePinCool.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePinCool.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePinCool.setObjectName("framePinCool")
        self.tablePinCool = QtWidgets.QTableWidget(self.framePinCool)
        self.tablePinCool.setEnabled(True)
        self.tablePinCool.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tablePinCool.setFont(font)
        self.tablePinCool.setMouseTracking(True)
        self.tablePinCool.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tablePinCool.setAutoFillBackground(False)
        self.tablePinCool.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tablePinCool.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tablePinCool.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tablePinCool.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablePinCool.setShowGrid(False)
        self.tablePinCool.setGridStyle(QtCore.Qt.SolidLine)
        self.tablePinCool.setObjectName("tablePinCool")
        self.tablePinCool.setColumnCount(2)
        self.tablePinCool.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePinCool.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePinCool.setHorizontalHeaderItem(1, item)
        self.tablePinCool.horizontalHeader().setVisible(False)
        self.tablePinCool.horizontalHeader().setCascadingSectionResizes(True)
        self.tablePinCool.horizontalHeader().setDefaultSectionSize(120)
        self.tablePinCool.horizontalHeader().setHighlightSections(False)
        self.tablePinCool.horizontalHeader().setMinimumSectionSize(15)
        self.tablePinCool.horizontalHeader().setSortIndicatorShown(True)
        self.tablePinCool.horizontalHeader().setStretchLastSection(False)
        self.tablePinCool.verticalHeader().setVisible(False)
        self.tablePinCool.verticalHeader().setCascadingSectionResizes(False)
        self.tablePinCool.verticalHeader().setMinimumSectionSize(10)
        self.btnResetPinCool = QtWidgets.QPushButton(self.framePinCool)
        self.btnResetPinCool.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetPinCool.setFont(font)
        self.btnResetPinCool.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(10, 10, 10);\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetPinCool.setObjectName("btnResetPinCool")
        self.toolBoxCoolFilter.addItem(self.pinCool, icon3, "")
        self.disperse = QtWidgets.QWidget()
        self.disperse.setGeometry(QtCore.QRect(0, 0, 307, 194))
        self.disperse.setObjectName("disperse")
        self.frameDisperse = QtWidgets.QFrame(self.disperse)
        self.frameDisperse.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameDisperse.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameDisperse.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDisperse.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDisperse.setObjectName("frameDisperse")
        self.btnResetDisperse = QtWidgets.QPushButton(self.frameDisperse)
        self.btnResetDisperse.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetDisperse.setFont(font)
        self.btnResetDisperse.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(10, 10, 10);\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetDisperse.setObjectName("btnResetDisperse")
        self.sliderDisperseMax = QtWidgets.QSlider(self.frameDisperse)
        self.sliderDisperseMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderDisperseMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderDisperseMax.setProperty("value", 0)
        self.sliderDisperseMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderDisperseMax.setInvertedAppearance(False)
        self.sliderDisperseMax.setInvertedControls(False)
        self.sliderDisperseMax.setObjectName("sliderDisperseMax")
        self.sliderDisperseMin = QtWidgets.QSlider(self.frameDisperse)
        self.sliderDisperseMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderDisperseMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderDisperseMin.setProperty("value", 0)
        self.sliderDisperseMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderDisperseMin.setInvertedAppearance(False)
        self.sliderDisperseMin.setInvertedControls(False)
        self.sliderDisperseMin.setObjectName("sliderDisperseMin")
        self.line_4 = QtWidgets.QFrame(self.frameDisperse)
        self.line_4.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_4.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lbMinDisperse = QtWidgets.QLabel(self.frameDisperse)
        self.lbMinDisperse.setGeometry(QtCore.QRect(10, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinDisperse.setFont(font)
        self.lbMinDisperse.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinDisperse.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinDisperse.setObjectName("lbMinDisperse")
        self.lbMaxDisperse = QtWidgets.QLabel(self.frameDisperse)
        self.lbMaxDisperse.setGeometry(QtCore.QRect(180, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxDisperse.setFont(font)
        self.lbMaxDisperse.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxDisperse.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxDisperse.setObjectName("lbMaxDisperse")
        self.leMinDisperse = QtWidgets.QLineEdit(self.frameDisperse)
        self.leMinDisperse.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinDisperse.setFont(font)
        self.leMinDisperse.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinDisperse.setObjectName("leMinDisperse")
        self.leMaxDisperse = QtWidgets.QLineEdit(self.frameDisperse)
        self.leMaxDisperse.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxDisperse.setFont(font)
        self.leMaxDisperse.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxDisperse.setObjectName("leMaxDisperse")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolBoxCoolFilter.addItem(self.disperse, icon4, "")
        self.height = QtWidgets.QWidget()
        self.height.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.height.setObjectName("height")
        self.framHeight = QtWidgets.QFrame(self.height)
        self.framHeight.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.framHeight.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.framHeight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framHeight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framHeight.setObjectName("framHeight")
        self.btnResetHeight = QtWidgets.QPushButton(self.framHeight)
        self.btnResetHeight.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetHeight.setFont(font)
        self.btnResetHeight.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(10, 10, 10);\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetHeight.setObjectName("btnResetHeight")
        self.line_5 = QtWidgets.QFrame(self.framHeight)
        self.line_5.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_5.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.sliderHeightMin = QtWidgets.QSlider(self.framHeight)
        self.sliderHeightMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderHeightMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderHeightMin.setProperty("value", 0)
        self.sliderHeightMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderHeightMin.setInvertedAppearance(False)
        self.sliderHeightMin.setInvertedControls(False)
        self.sliderHeightMin.setObjectName("sliderHeightMin")
        self.lbMaxHeight = QtWidgets.QLabel(self.framHeight)
        self.lbMaxHeight.setGeometry(QtCore.QRect(180, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxHeight.setFont(font)
        self.lbMaxHeight.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxHeight.setObjectName("lbMaxHeight")
        self.lbMinHeight = QtWidgets.QLabel(self.framHeight)
        self.lbMinHeight.setGeometry(QtCore.QRect(10, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinHeight.setFont(font)
        self.lbMinHeight.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinHeight.setObjectName("lbMinHeight")
        self.sliderHeightMax = QtWidgets.QSlider(self.framHeight)
        self.sliderHeightMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderHeightMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderHeightMax.setProperty("value", 0)
        self.sliderHeightMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderHeightMax.setInvertedAppearance(False)
        self.sliderHeightMax.setInvertedControls(False)
        self.sliderHeightMax.setObjectName("sliderHeightMax")
        self.leMaxHeight = QtWidgets.QLineEdit(self.framHeight)
        self.leMaxHeight.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxHeight.setFont(font)
        self.leMaxHeight.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxHeight.setObjectName("leMaxHeight")
        self.leMinHeight = QtWidgets.QLineEdit(self.framHeight)
        self.leMinHeight.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinHeight.setFont(font)
        self.leMinHeight.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinHeight.setObjectName("leMinHeight")
        self.toolBoxCoolFilter.addItem(self.height, icon3, "")
        self.line = QtWidgets.QFrame(WidgetCoolFilter)
        self.line.setGeometry(QtCore.QRect(40, 70, 181, 20))
        self.line.setStyleSheet("border:0px;\n"
"border-top: 1px solid red;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbFilter = QtWidgets.QLabel(WidgetCoolFilter)
        self.lbFilter.setGeometry(QtCore.QRect(40, 40, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lbFilter.setFont(font)
        self.lbFilter.setStyleSheet("border:0px;")
        self.lbFilter.setObjectName("lbFilter")

        self.retranslateUi(WidgetCoolFilter)
        self.toolBoxCoolFilter.layout().setSpacing(6)
        self.btnClose.clicked.connect(WidgetCoolFilter.close)
        QtCore.QMetaObject.connectSlotsByName(WidgetCoolFilter)

    def retranslateUi(self, WidgetCoolFilter):
        _translate = QtCore.QCoreApplication.translate
        WidgetCoolFilter.setWindowTitle(_translate("WidgetCoolFilter", "Фильтр охлаждения"))
        self.btnAccept.setText(_translate("WidgetCoolFilter", "Применить"))
        self.btnClose.setText(_translate("WidgetCoolFilter", "Отмена"))
        self.btnResetAll.setText(_translate("WidgetCoolFilter", "Сбросить всё"))
        self.btnResetPrice.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.lbMinPrice.setText(_translate("WidgetCoolFilter", "мин., ₽:"))
        self.lbMaxPrice.setText(_translate("WidgetCoolFilter", "макс., ₽:"))
        self.leMinPrice.setPlaceholderText(_translate("WidgetCoolFilter", "от 0"))
        self.leMaxPrice.setPlaceholderText(_translate("WidgetCoolFilter", "до 78499"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.price), _translate("WidgetCoolFilter", "Цена, ₽"))
        self.tableProizv.setSortingEnabled(True)
        item = self.tableProizv.horizontalHeaderItem(0)
        item.setText(_translate("WidgetCoolFilter", "Выбор"))
        item = self.tableProizv.horizontalHeaderItem(1)
        item.setText(_translate("WidgetCoolFilter", "Название"))
        self.btnResetProizv.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.proizvoditel), _translate("WidgetCoolFilter", "Производитель охлаждения"))
        self.tableConstr.setSortingEnabled(True)
        item = self.tableConstr.horizontalHeaderItem(0)
        item.setText(_translate("WidgetCoolFilter", "Выбор"))
        item = self.tableConstr.horizontalHeaderItem(1)
        item.setText(_translate("WidgetCoolFilter", "Название"))
        self.btnResetConstr.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.construction), _translate("WidgetCoolFilter", "Конструкция"))
        self.tableSocket.setSortingEnabled(True)
        item = self.tableSocket.horizontalHeaderItem(0)
        item.setText(_translate("WidgetCoolFilter", "Выбор"))
        item = self.tableSocket.horizontalHeaderItem(1)
        item.setText(_translate("WidgetCoolFilter", "Название"))
        self.btnResetSocket.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.socket), _translate("WidgetCoolFilter", "Сокет"))
        self.tableType.setSortingEnabled(True)
        item = self.tableType.horizontalHeaderItem(0)
        item.setText(_translate("WidgetCoolFilter", "Выбор"))
        item = self.tableType.horizontalHeaderItem(1)
        item.setText(_translate("WidgetCoolFilter", "Название"))
        self.btnResetType.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.type), _translate("WidgetCoolFilter", "Тип охлаждения"))
        self.tablePipe.setSortingEnabled(True)
        item = self.tablePipe.horizontalHeaderItem(0)
        item.setText(_translate("WidgetCoolFilter", "Выбор"))
        item = self.tablePipe.horizontalHeaderItem(1)
        item.setText(_translate("WidgetCoolFilter", "Название"))
        self.btnResetPipe.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.heatpipe), _translate("WidgetCoolFilter", "Тепловые трубы"))
        self.tablePinCool.setSortingEnabled(True)
        item = self.tablePinCool.horizontalHeaderItem(0)
        item.setText(_translate("WidgetCoolFilter", "Выбор"))
        item = self.tablePinCool.horizontalHeaderItem(1)
        item.setText(_translate("WidgetCoolFilter", "Название"))
        self.btnResetPinCool.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.pinCool), _translate("WidgetCoolFilter", "Pin-коннекторы охлаждения"))
        self.btnResetDisperse.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.lbMinDisperse.setText(_translate("WidgetCoolFilter", "мин., Вт:"))
        self.lbMaxDisperse.setText(_translate("WidgetCoolFilter", "макс., Вт:"))
        self.leMinDisperse.setPlaceholderText(_translate("WidgetCoolFilter", "от 0 Вт"))
        self.leMaxDisperse.setPlaceholderText(_translate("WidgetCoolFilter", "до 200 Вт"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.disperse), _translate("WidgetCoolFilter", "Рассеиваемость [Вт]"))
        self.btnResetHeight.setText(_translate("WidgetCoolFilter", "Сбросить"))
        self.lbMaxHeight.setText(_translate("WidgetCoolFilter", "макс., мм:"))
        self.lbMinHeight.setText(_translate("WidgetCoolFilter", "мин., мм:"))
        self.leMaxHeight.setPlaceholderText(_translate("WidgetCoolFilter", "до 300 мм"))
        self.leMinHeight.setPlaceholderText(_translate("WidgetCoolFilter", "от 0 мм"))
        self.toolBoxCoolFilter.setItemText(self.toolBoxCoolFilter.indexOf(self.height), _translate("WidgetCoolFilter", "Высота кулера [мм]"))
        self.lbFilter.setText(_translate("WidgetCoolFilter", "Настройка фильтров"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetCoolFilter = QtWidgets.QWidget()
    ui = Ui_WidgetCoolFilter()
    ui.setupUi(WidgetCoolFilter)
    WidgetCoolFilter.show()
    sys.exit(app.exec_())
