# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\filter\widgetRamFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetRamFilter(object):
    def setupUi(self, WidgetRamFilter):
        WidgetRamFilter.setObjectName("WidgetRamFilter")
        WidgetRamFilter.resize(373, 651)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/filters.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WidgetRamFilter.setWindowIcon(icon)
        WidgetRamFilter.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(30,30,30);\n"
"    color: white;\n"
"\n"
"}\n"
"")
        self.btnResetAll = QtWidgets.QPushButton(WidgetRamFilter)
        self.btnResetAll.setGeometry(QtCore.QRect(250, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetAll.setFont(font)
        self.btnResetAll.setStyleSheet("QPushButton\n"
"{\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetAll.setObjectName("btnResetAll")
        self.toolBoxRamFilter = QtWidgets.QToolBox(WidgetRamFilter)
        self.toolBoxRamFilter.setGeometry(QtCore.QRect(30, 90, 311, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxRamFilter.sizePolicy().hasHeightForWidth())
        self.toolBoxRamFilter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.toolBoxRamFilter.setFont(font)
        self.toolBoxRamFilter.setAccessibleName("")
        self.toolBoxRamFilter.setStyleSheet("QToolBox\n"
"{\n"
"    background: rgb(30, 30, 30);\n"
"    border: 1px solid red;\n"
"    margin: 1px;\n"
"    icon-size: 23px;\n"
"}\n"
"\n"
"QToolBox::tab\n"
"{\n"
"    height:250px;\n"
"    background: rgb(30, 30, 30);\n"
"    margin-left: 1px;\n"
"    left: -1px;\n"
"    color: rgb(235, 235, 235);\n"
"    border-top: 1px solid;\n"
"    border-bottom: 3px solid;\n"
"}\n"
"\n"
"QToolBox::tab:selected\n"
"{\n"
"    background-color: rgb(45, 45, 45);\n"
"    border-bottom: 2px solid  rgb(180, 0, 0);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBox::tab:hover\n"
"{\n"
"    background-color: rgb(65, 65, 65);\n"
"    border-bottom: 5px solid;\n"
"    border-color: black;\n"
"}\n"
"")
        self.toolBoxRamFilter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBoxRamFilter.setLineWidth(0)
        self.toolBoxRamFilter.setMidLineWidth(1)
        self.toolBoxRamFilter.setObjectName("toolBoxRamFilter")
        self.price = QtWidgets.QWidget()
        self.price.setGeometry(QtCore.QRect(0, 0, 307, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.price.setSizeIncrement(QtCore.QSize(0, 0))
        self.price.setBaseSize(QtCore.QSize(0, 200))
        self.price.setObjectName("price")
        self.tbFrameProc = QtWidgets.QFrame(self.price)
        self.tbFrameProc.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.tbFrameProc.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}")
        self.tbFrameProc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbFrameProc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbFrameProc.setObjectName("tbFrameProc")
        self.sliderPriceMin = QtWidgets.QSlider(self.tbFrameProc)
        self.sliderPriceMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderPriceMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderPriceMin.setProperty("value", 0)
        self.sliderPriceMin.setTracking(True)
        self.sliderPriceMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPriceMin.setInvertedAppearance(False)
        self.sliderPriceMin.setInvertedControls(False)
        self.sliderPriceMin.setObjectName("sliderPriceMin")
        self.line_2 = QtWidgets.QFrame(self.tbFrameProc)
        self.line_2.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_2.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.sliderPriceMax = QtWidgets.QSlider(self.tbFrameProc)
        self.sliderPriceMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderPriceMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderPriceMax.setProperty("value", 0)
        self.sliderPriceMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPriceMax.setInvertedAppearance(False)
        self.sliderPriceMax.setInvertedControls(False)
        self.sliderPriceMax.setObjectName("sliderPriceMax")
        self.btnResetPrice = QtWidgets.QPushButton(self.tbFrameProc)
        self.btnResetPrice.setGeometry(QtCore.QRect(220, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetPrice.setFont(font)
        self.btnResetPrice.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetPrice.setObjectName("btnResetPrice")
        self.lbMinPrice = QtWidgets.QLabel(self.tbFrameProc)
        self.lbMinPrice.setGeometry(QtCore.QRect(10, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinPrice.setFont(font)
        self.lbMinPrice.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinPrice.setObjectName("lbMinPrice")
        self.lbMaxPrice = QtWidgets.QLabel(self.tbFrameProc)
        self.lbMaxPrice.setGeometry(QtCore.QRect(180, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxPrice.setFont(font)
        self.lbMaxPrice.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxPrice.setObjectName("lbMaxPrice")
        self.leMinPrice = QtWidgets.QLineEdit(self.tbFrameProc)
        self.leMinPrice.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinPrice.setFont(font)
        self.leMinPrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinPrice.setObjectName("leMinPrice")
        self.leMaxPrice = QtWidgets.QLineEdit(self.tbFrameProc)
        self.leMaxPrice.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxPrice.setFont(font)
        self.leMaxPrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxPrice.setObjectName("leMaxPrice")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.toolBoxRamFilter.addItem(self.price, icon1, "")
        self.proizvoditel = QtWidgets.QWidget()
        self.proizvoditel.setGeometry(QtCore.QRect(0, 0, 307, 191))
        self.proizvoditel.setObjectName("proizvoditel")
        self.frameProizv = QtWidgets.QFrame(self.proizvoditel)
        self.frameProizv.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameProizv.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameProizv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProizv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProizv.setObjectName("frameProizv")
        self.tableProizv = QtWidgets.QTableWidget(self.frameProizv)
        self.tableProizv.setEnabled(True)
        self.tableProizv.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableProizv.setFont(font)
        self.tableProizv.setMouseTracking(True)
        self.tableProizv.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableProizv.setAutoFillBackground(False)
        self.tableProizv.setStyleSheet("QTableWidget::item\n"
"{\n"
"    background: rgb(10, 10, 10);\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background: rgb(10, 10, 10);\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableProizv.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableProizv.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableProizv.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProizv.setShowGrid(False)
        self.tableProizv.setGridStyle(QtCore.Qt.SolidLine)
        self.tableProizv.setObjectName("tableProizv")
        self.tableProizv.setColumnCount(2)
        self.tableProizv.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProizv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProizv.setHorizontalHeaderItem(1, item)
        self.tableProizv.horizontalHeader().setVisible(False)
        self.tableProizv.horizontalHeader().setCascadingSectionResizes(True)
        self.tableProizv.horizontalHeader().setDefaultSectionSize(120)
        self.tableProizv.horizontalHeader().setHighlightSections(False)
        self.tableProizv.horizontalHeader().setMinimumSectionSize(15)
        self.tableProizv.horizontalHeader().setSortIndicatorShown(True)
        self.tableProizv.horizontalHeader().setStretchLastSection(False)
        self.tableProizv.verticalHeader().setVisible(False)
        self.tableProizv.verticalHeader().setCascadingSectionResizes(False)
        self.tableProizv.verticalHeader().setMinimumSectionSize(10)
        self.btnResetProizv = QtWidgets.QPushButton(self.frameProizv)
        self.btnResetProizv.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetProizv.setFont(font)
        self.btnResetProizv.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetProizv.setObjectName("btnResetProizv")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/up-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.toolBoxRamFilter.addItem(self.proizvoditel, icon2, "")
        self.type = QtWidgets.QWidget()
        self.type.setGeometry(QtCore.QRect(0, 0, 307, 191))
        self.type.setObjectName("type")
        self.frameType = QtWidgets.QFrame(self.type)
        self.frameType.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameType.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameType.setObjectName("frameType")
        self.tableType = QtWidgets.QTableWidget(self.frameType)
        self.tableType.setEnabled(True)
        self.tableType.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableType.setFont(font)
        self.tableType.setMouseTracking(True)
        self.tableType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableType.setAutoFillBackground(False)
        self.tableType.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableType.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableType.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableType.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableType.setShowGrid(False)
        self.tableType.setGridStyle(QtCore.Qt.SolidLine)
        self.tableType.setObjectName("tableType")
        self.tableType.setColumnCount(2)
        self.tableType.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableType.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableType.setHorizontalHeaderItem(1, item)
        self.tableType.horizontalHeader().setVisible(False)
        self.tableType.horizontalHeader().setCascadingSectionResizes(True)
        self.tableType.horizontalHeader().setDefaultSectionSize(120)
        self.tableType.horizontalHeader().setHighlightSections(False)
        self.tableType.horizontalHeader().setMinimumSectionSize(15)
        self.tableType.horizontalHeader().setSortIndicatorShown(True)
        self.tableType.horizontalHeader().setStretchLastSection(False)
        self.tableType.verticalHeader().setVisible(False)
        self.tableType.verticalHeader().setCascadingSectionResizes(False)
        self.tableType.verticalHeader().setMinimumSectionSize(10)
        self.btnResetType = QtWidgets.QPushButton(self.frameType)
        self.btnResetType.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetType.setFont(font)
        self.btnResetType.setStyleSheet("QPushButton\n"
"{    \n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetType.setObjectName("btnResetType")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBoxRamFilter.addItem(self.type, icon3, "")
        self.gaming = QtWidgets.QWidget()
        self.gaming.setGeometry(QtCore.QRect(0, 0, 307, 191))
        self.gaming.setObjectName("gaming")
        self.frameGaming = QtWidgets.QFrame(self.gaming)
        self.frameGaming.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameGaming.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameGaming.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGaming.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGaming.setObjectName("frameGaming")
        self.tableGaming = QtWidgets.QTableWidget(self.frameGaming)
        self.tableGaming.setEnabled(True)
        self.tableGaming.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableGaming.setFont(font)
        self.tableGaming.setMouseTracking(True)
        self.tableGaming.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableGaming.setAutoFillBackground(False)
        self.tableGaming.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableGaming.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableGaming.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableGaming.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableGaming.setShowGrid(False)
        self.tableGaming.setGridStyle(QtCore.Qt.SolidLine)
        self.tableGaming.setObjectName("tableGaming")
        self.tableGaming.setColumnCount(2)
        self.tableGaming.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableGaming.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableGaming.setHorizontalHeaderItem(1, item)
        self.tableGaming.horizontalHeader().setVisible(False)
        self.tableGaming.horizontalHeader().setCascadingSectionResizes(True)
        self.tableGaming.horizontalHeader().setDefaultSectionSize(120)
        self.tableGaming.horizontalHeader().setHighlightSections(False)
        self.tableGaming.horizontalHeader().setMinimumSectionSize(15)
        self.tableGaming.horizontalHeader().setSortIndicatorShown(True)
        self.tableGaming.horizontalHeader().setStretchLastSection(False)
        self.tableGaming.verticalHeader().setVisible(False)
        self.tableGaming.verticalHeader().setCascadingSectionResizes(False)
        self.tableGaming.verticalHeader().setMinimumSectionSize(10)
        self.btnResetGaming = QtWidgets.QPushButton(self.frameGaming)
        self.btnResetGaming.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetGaming.setFont(font)
        self.btnResetGaming.setStyleSheet("QPushButton\n"
"{    \n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetGaming.setObjectName("btnResetGaming")
        self.toolBoxRamFilter.addItem(self.gaming, icon3, "")
        self.volume = QtWidgets.QWidget()
        self.volume.setGeometry(QtCore.QRect(0, 0, 307, 191))
        self.volume.setObjectName("volume")
        self.frameVolume = QtWidgets.QFrame(self.volume)
        self.frameVolume.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameVolume.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameVolume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVolume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVolume.setObjectName("frameVolume")
        self.tableVolume = QtWidgets.QTableWidget(self.frameVolume)
        self.tableVolume.setEnabled(True)
        self.tableVolume.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableVolume.setFont(font)
        self.tableVolume.setMouseTracking(True)
        self.tableVolume.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableVolume.setAutoFillBackground(False)
        self.tableVolume.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableVolume.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableVolume.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableVolume.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableVolume.setShowGrid(False)
        self.tableVolume.setGridStyle(QtCore.Qt.SolidLine)
        self.tableVolume.setObjectName("tableVolume")
        self.tableVolume.setColumnCount(2)
        self.tableVolume.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableVolume.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVolume.setHorizontalHeaderItem(1, item)
        self.tableVolume.horizontalHeader().setVisible(False)
        self.tableVolume.horizontalHeader().setCascadingSectionResizes(True)
        self.tableVolume.horizontalHeader().setDefaultSectionSize(120)
        self.tableVolume.horizontalHeader().setHighlightSections(False)
        self.tableVolume.horizontalHeader().setMinimumSectionSize(15)
        self.tableVolume.horizontalHeader().setSortIndicatorShown(True)
        self.tableVolume.horizontalHeader().setStretchLastSection(False)
        self.tableVolume.verticalHeader().setVisible(False)
        self.tableVolume.verticalHeader().setCascadingSectionResizes(False)
        self.tableVolume.verticalHeader().setMinimumSectionSize(10)
        self.btnResetVolume = QtWidgets.QPushButton(self.frameVolume)
        self.btnResetVolume.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetVolume.setFont(font)
        self.btnResetVolume.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetVolume.setObjectName("btnResetVolume")
        self.toolBoxRamFilter.addItem(self.volume, icon3, "")
        self.frequency = QtWidgets.QWidget()
        self.frequency.setGeometry(QtCore.QRect(0, 0, 307, 191))
        self.frequency.setObjectName("frequency")
        self.frameFreq = QtWidgets.QFrame(self.frequency)
        self.frameFreq.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameFreq.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameFreq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFreq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFreq.setObjectName("frameFreq")
        self.tableFreq = QtWidgets.QTableWidget(self.frameFreq)
        self.tableFreq.setEnabled(True)
        self.tableFreq.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableFreq.setFont(font)
        self.tableFreq.setMouseTracking(True)
        self.tableFreq.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableFreq.setAutoFillBackground(False)
        self.tableFreq.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableFreq.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableFreq.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableFreq.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableFreq.setShowGrid(False)
        self.tableFreq.setGridStyle(QtCore.Qt.SolidLine)
        self.tableFreq.setObjectName("tableFreq")
        self.tableFreq.setColumnCount(2)
        self.tableFreq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFreq.setHorizontalHeaderItem(1, item)
        self.tableFreq.horizontalHeader().setVisible(False)
        self.tableFreq.horizontalHeader().setCascadingSectionResizes(True)
        self.tableFreq.horizontalHeader().setDefaultSectionSize(120)
        self.tableFreq.horizontalHeader().setHighlightSections(False)
        self.tableFreq.horizontalHeader().setMinimumSectionSize(15)
        self.tableFreq.horizontalHeader().setSortIndicatorShown(True)
        self.tableFreq.horizontalHeader().setStretchLastSection(False)
        self.tableFreq.verticalHeader().setVisible(False)
        self.tableFreq.verticalHeader().setCascadingSectionResizes(False)
        self.tableFreq.verticalHeader().setMinimumSectionSize(10)
        self.btnResetFreq = QtWidgets.QPushButton(self.frameFreq)
        self.btnResetFreq.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetFreq.setFont(font)
        self.btnResetFreq.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(10, 10, 10);\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetFreq.setObjectName("btnResetFreq")
        self.toolBoxRamFilter.addItem(self.frequency, icon3, "")
        self.module = QtWidgets.QWidget()
        self.module.setGeometry(QtCore.QRect(0, 0, 307, 191))
        self.module.setObjectName("module")
        self.frameModule = QtWidgets.QFrame(self.module)
        self.frameModule.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameModule.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameModule.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameModule.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameModule.setObjectName("frameModule")
        self.tableModule = QtWidgets.QTableWidget(self.frameModule)
        self.tableModule.setEnabled(True)
        self.tableModule.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableModule.setFont(font)
        self.tableModule.setMouseTracking(True)
        self.tableModule.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableModule.setAutoFillBackground(False)
        self.tableModule.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableModule.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableModule.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableModule.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableModule.setShowGrid(False)
        self.tableModule.setGridStyle(QtCore.Qt.SolidLine)
        self.tableModule.setObjectName("tableModule")
        self.tableModule.setColumnCount(2)
        self.tableModule.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableModule.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableModule.setHorizontalHeaderItem(1, item)
        self.tableModule.horizontalHeader().setVisible(False)
        self.tableModule.horizontalHeader().setCascadingSectionResizes(True)
        self.tableModule.horizontalHeader().setDefaultSectionSize(120)
        self.tableModule.horizontalHeader().setHighlightSections(False)
        self.tableModule.horizontalHeader().setMinimumSectionSize(15)
        self.tableModule.horizontalHeader().setSortIndicatorShown(True)
        self.tableModule.horizontalHeader().setStretchLastSection(False)
        self.tableModule.verticalHeader().setVisible(False)
        self.tableModule.verticalHeader().setCascadingSectionResizes(False)
        self.tableModule.verticalHeader().setMinimumSectionSize(10)
        self.btnResetModule = QtWidgets.QPushButton(self.frameModule)
        self.btnResetModule.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetModule.setFont(font)
        self.btnResetModule.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(10, 10, 10);\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetModule.setObjectName("btnResetModule")
        self.toolBoxRamFilter.addItem(self.module, icon3, "")
        self.latency = QtWidgets.QWidget()
        self.latency.setGeometry(QtCore.QRect(0, 0, 307, 191))
        self.latency.setObjectName("latency")
        self.frameLatency = QtWidgets.QFrame(self.latency)
        self.frameLatency.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameLatency.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameLatency.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLatency.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLatency.setObjectName("frameLatency")
        self.tableLatency = QtWidgets.QTableWidget(self.frameLatency)
        self.tableLatency.setEnabled(True)
        self.tableLatency.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableLatency.setFont(font)
        self.tableLatency.setMouseTracking(True)
        self.tableLatency.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableLatency.setAutoFillBackground(False)
        self.tableLatency.setStyleSheet("QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableLatency.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableLatency.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableLatency.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableLatency.setShowGrid(False)
        self.tableLatency.setGridStyle(QtCore.Qt.SolidLine)
        self.tableLatency.setObjectName("tableLatency")
        self.tableLatency.setColumnCount(2)
        self.tableLatency.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableLatency.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLatency.setHorizontalHeaderItem(1, item)
        self.tableLatency.horizontalHeader().setVisible(False)
        self.tableLatency.horizontalHeader().setCascadingSectionResizes(True)
        self.tableLatency.horizontalHeader().setDefaultSectionSize(120)
        self.tableLatency.horizontalHeader().setHighlightSections(False)
        self.tableLatency.horizontalHeader().setMinimumSectionSize(15)
        self.tableLatency.horizontalHeader().setSortIndicatorShown(True)
        self.tableLatency.horizontalHeader().setStretchLastSection(False)
        self.tableLatency.verticalHeader().setVisible(False)
        self.tableLatency.verticalHeader().setCascadingSectionResizes(False)
        self.tableLatency.verticalHeader().setMinimumSectionSize(10)
        self.btnResetLatency = QtWidgets.QPushButton(self.frameLatency)
        self.btnResetLatency.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetLatency.setFont(font)
        self.btnResetLatency.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(10, 10, 10);\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetLatency.setObjectName("btnResetLatency")
        self.toolBoxRamFilter.addItem(self.latency, icon3, "")
        self.line = QtWidgets.QFrame(WidgetRamFilter)
        self.line.setGeometry(QtCore.QRect(40, 70, 181, 20))
        self.line.setStyleSheet("border:0px;\n"
"border-top: 1px solid red;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbFilter = QtWidgets.QLabel(WidgetRamFilter)
        self.lbFilter.setGeometry(QtCore.QRect(40, 40, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lbFilter.setFont(font)
        self.lbFilter.setStyleSheet("border:0px;")
        self.lbFilter.setObjectName("lbFilter")
        self.btnClose = QtWidgets.QPushButton(WidgetRamFilter)
        self.btnClose.setGeometry(QtCore.QRect(190, 600, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnClose.setObjectName("btnClose")
        self.btnAccept = QtWidgets.QPushButton(WidgetRamFilter)
        self.btnAccept.setGeometry(QtCore.QRect(60, 600, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnAccept.setFont(font)
        self.btnAccept.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"}\n"
"")
        self.btnAccept.setObjectName("btnAccept")
        self.rectangle = QtWidgets.QFrame(WidgetRamFilter)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")

        self.retranslateUi(WidgetRamFilter)
        self.toolBoxRamFilter.layout().setSpacing(6)
        self.btnClose.clicked.connect(WidgetRamFilter.close)
        QtCore.QMetaObject.connectSlotsByName(WidgetRamFilter)

    def retranslateUi(self, WidgetRamFilter):
        _translate = QtCore.QCoreApplication.translate
        WidgetRamFilter.setWindowTitle(_translate("WidgetRamFilter", "Фильтр ОЗУ"))
        self.btnResetAll.setText(_translate("WidgetRamFilter", "Сбросить всё"))
        self.btnResetPrice.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.lbMinPrice.setText(_translate("WidgetRamFilter", "мин., ₽:"))
        self.lbMaxPrice.setText(_translate("WidgetRamFilter", "макс., ₽:"))
        self.leMinPrice.setPlaceholderText(_translate("WidgetRamFilter", "от 0"))
        self.leMaxPrice.setPlaceholderText(_translate("WidgetRamFilter", "до 78499"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.price), _translate("WidgetRamFilter", "Цена, ₽"))
        self.tableProizv.setSortingEnabled(True)
        item = self.tableProizv.horizontalHeaderItem(0)
        item.setText(_translate("WidgetRamFilter", "Выбор"))
        item = self.tableProizv.horizontalHeaderItem(1)
        item.setText(_translate("WidgetRamFilter", "Название"))
        self.btnResetProizv.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.proizvoditel), _translate("WidgetRamFilter", "Производитель ОЗУ"))
        self.tableType.setSortingEnabled(True)
        item = self.tableType.horizontalHeaderItem(0)
        item.setText(_translate("WidgetRamFilter", "Выбор"))
        item = self.tableType.horizontalHeaderItem(1)
        item.setText(_translate("WidgetRamFilter", "Название"))
        self.btnResetType.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.type), _translate("WidgetRamFilter", "Тип ОЗУ"))
        self.tableGaming.setSortingEnabled(True)
        item = self.tableGaming.horizontalHeaderItem(0)
        item.setText(_translate("WidgetRamFilter", "Выбор"))
        item = self.tableGaming.horizontalHeaderItem(1)
        item.setText(_translate("WidgetRamFilter", "Название"))
        self.btnResetGaming.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.gaming), _translate("WidgetRamFilter", "Игровое комплектующее"))
        self.tableVolume.setSortingEnabled(True)
        item = self.tableVolume.horizontalHeaderItem(0)
        item.setText(_translate("WidgetRamFilter", "Выбор"))
        item = self.tableVolume.horizontalHeaderItem(1)
        item.setText(_translate("WidgetRamFilter", "Название"))
        self.btnResetVolume.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.volume), _translate("WidgetRamFilter", "Объём комплекта [Гб]"))
        self.tableFreq.setSortingEnabled(True)
        item = self.tableFreq.horizontalHeaderItem(0)
        item.setText(_translate("WidgetRamFilter", "Выбор"))
        item = self.tableFreq.horizontalHeaderItem(1)
        item.setText(_translate("WidgetRamFilter", "Название"))
        self.btnResetFreq.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.frequency), _translate("WidgetRamFilter", "Тактовая частота [Гц]"))
        self.tableModule.setSortingEnabled(True)
        item = self.tableModule.horizontalHeaderItem(0)
        item.setText(_translate("WidgetRamFilter", "Выбор"))
        item = self.tableModule.horizontalHeaderItem(1)
        item.setText(_translate("WidgetRamFilter", "Название"))
        self.btnResetModule.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.module), _translate("WidgetRamFilter", "Кол-во модулей"))
        self.tableLatency.setSortingEnabled(True)
        item = self.tableLatency.horizontalHeaderItem(0)
        item.setText(_translate("WidgetRamFilter", "Выбор"))
        item = self.tableLatency.horizontalHeaderItem(1)
        item.setText(_translate("WidgetRamFilter", "Название"))
        self.btnResetLatency.setText(_translate("WidgetRamFilter", "Сбросить"))
        self.toolBoxRamFilter.setItemText(self.toolBoxRamFilter.indexOf(self.latency), _translate("WidgetRamFilter", "CAS-Latency"))
        self.lbFilter.setText(_translate("WidgetRamFilter", "Настройка фильтров"))
        self.btnClose.setText(_translate("WidgetRamFilter", "Отмена"))
        self.btnAccept.setText(_translate("WidgetRamFilter", "Применить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetRamFilter = QtWidgets.QWidget()
    ui = Ui_WidgetRamFilter()
    ui.setupUi(WidgetRamFilter)
    WidgetRamFilter.show()
    sys.exit(app.exec_())
