# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\filter\widgetDiskFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDiskFilter(object):
    def setupUi(self, WidgetDiskFilter):
        WidgetDiskFilter.setObjectName("WidgetDiskFilter")
        WidgetDiskFilter.resize(374, 605)
        WidgetDiskFilter.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(30,30,30);\n"
"    color: white;\n"
"\n"
"}\n"
"")
        self.btnAccept = QtWidgets.QPushButton(WidgetDiskFilter)
        self.btnAccept.setGeometry(QtCore.QRect(60, 560, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnAccept.setFont(font)
        self.btnAccept.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"}\n"
"")
        self.btnAccept.setObjectName("btnAccept")
        self.btnClose = QtWidgets.QPushButton(WidgetDiskFilter)
        self.btnClose.setGeometry(QtCore.QRect(190, 560, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnClose.setObjectName("btnClose")
        self.rectangle = QtWidgets.QFrame(WidgetDiskFilter)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.lbFilter = QtWidgets.QLabel(WidgetDiskFilter)
        self.lbFilter.setGeometry(QtCore.QRect(40, 40, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lbFilter.setFont(font)
        self.lbFilter.setStyleSheet("border:0px;")
        self.lbFilter.setObjectName("lbFilter")
        self.btnResetAll = QtWidgets.QPushButton(WidgetDiskFilter)
        self.btnResetAll.setGeometry(QtCore.QRect(250, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetAll.setFont(font)
        self.btnResetAll.setStyleSheet("QPushButton\n"
"{\n"
"color:  rgb(200,200, 200);\n"
"border: 0px;\n"
"border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: red;\n"
"border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetAll.setObjectName("btnResetAll")
        self.line = QtWidgets.QFrame(WidgetDiskFilter)
        self.line.setGeometry(QtCore.QRect(40, 70, 181, 20))
        self.line.setStyleSheet("border:0px;\n"
"border-top: 1px solid red;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.toolBoxDiskFilter = QtWidgets.QToolBox(WidgetDiskFilter)
        self.toolBoxDiskFilter.setGeometry(QtCore.QRect(30, 90, 311, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxDiskFilter.sizePolicy().hasHeightForWidth())
        self.toolBoxDiskFilter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.toolBoxDiskFilter.setFont(font)
        self.toolBoxDiskFilter.setAccessibleName("")
        self.toolBoxDiskFilter.setStyleSheet("QToolBox\n"
"{\n"
"    background: rgb(30, 30, 30);\n"
"    border: 1px solid red;\n"
"    margin: 1px;\n"
"    icon-size: 23px;\n"
"}\n"
"\n"
"QToolBox::tab\n"
"{\n"
"    height:250px;\n"
"    background: rgb(30, 30, 30);\n"
"    margin-left: 1px;\n"
"    left: -1px;\n"
"    color: rgb(235, 235, 235);\n"
"    border-top: 1px solid;\n"
"    border-bottom: 3px solid;\n"
"}\n"
"\n"
"QToolBox::tab:selected\n"
"{\n"
"    background-color: rgb(45, 45, 45);\n"
"    border-bottom: 2px solid  rgb(180, 0, 0);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBox::tab:hover\n"
"{\n"
"    background-color: rgb(65, 65, 65);\n"
"    border-bottom: 5px solid;\n"
"    border-color: black;\n"
"}\n"
"")
        self.toolBoxDiskFilter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBoxDiskFilter.setLineWidth(0)
        self.toolBoxDiskFilter.setMidLineWidth(1)
        self.toolBoxDiskFilter.setObjectName("toolBoxDiskFilter")
        self.price = QtWidgets.QWidget()
        self.price.setGeometry(QtCore.QRect(0, 0, 307, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.price.setSizeIncrement(QtCore.QSize(0, 0))
        self.price.setBaseSize(QtCore.QSize(0, 200))
        self.price.setObjectName("price")
        self.tbFrameProc = QtWidgets.QFrame(self.price)
        self.tbFrameProc.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.tbFrameProc.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}")
        self.tbFrameProc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbFrameProc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbFrameProc.setObjectName("tbFrameProc")
        self.sliderPriceMin = QtWidgets.QSlider(self.tbFrameProc)
        self.sliderPriceMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderPriceMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderPriceMin.setProperty("value", 0)
        self.sliderPriceMin.setTracking(True)
        self.sliderPriceMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPriceMin.setInvertedAppearance(False)
        self.sliderPriceMin.setInvertedControls(False)
        self.sliderPriceMin.setObjectName("sliderPriceMin")
        self.line_2 = QtWidgets.QFrame(self.tbFrameProc)
        self.line_2.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_2.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.sliderPriceMax = QtWidgets.QSlider(self.tbFrameProc)
        self.sliderPriceMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderPriceMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderPriceMax.setProperty("value", 0)
        self.sliderPriceMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPriceMax.setInvertedAppearance(False)
        self.sliderPriceMax.setInvertedControls(False)
        self.sliderPriceMax.setObjectName("sliderPriceMax")
        self.btnResetPrice = QtWidgets.QPushButton(self.tbFrameProc)
        self.btnResetPrice.setGeometry(QtCore.QRect(220, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetPrice.setFont(font)
        self.btnResetPrice.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetPrice.setObjectName("btnResetPrice")
        self.lbMinPrice = QtWidgets.QLabel(self.tbFrameProc)
        self.lbMinPrice.setGeometry(QtCore.QRect(10, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinPrice.setFont(font)
        self.lbMinPrice.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinPrice.setObjectName("lbMinPrice")
        self.lbMaxPrice = QtWidgets.QLabel(self.tbFrameProc)
        self.lbMaxPrice.setGeometry(QtCore.QRect(180, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxPrice.setFont(font)
        self.lbMaxPrice.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxPrice.setObjectName("lbMaxPrice")
        self.leMinPrice = QtWidgets.QLineEdit(self.tbFrameProc)
        self.leMinPrice.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinPrice.setFont(font)
        self.leMinPrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinPrice.setObjectName("leMinPrice")
        self.leMaxPrice = QtWidgets.QLineEdit(self.tbFrameProc)
        self.leMaxPrice.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxPrice.setFont(font)
        self.leMaxPrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxPrice.setObjectName("leMaxPrice")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow (1).png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.toolBoxDiskFilter.addItem(self.price, icon, "")
        self.proizvoditel = QtWidgets.QWidget()
        self.proizvoditel.setGeometry(QtCore.QRect(0, 0, 307, 188))
        self.proizvoditel.setObjectName("proizvoditel")
        self.frameProizv = QtWidgets.QFrame(self.proizvoditel)
        self.frameProizv.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameProizv.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameProizv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProizv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProizv.setObjectName("frameProizv")
        self.tableProizv = QtWidgets.QTableWidget(self.frameProizv)
        self.tableProizv.setEnabled(True)
        self.tableProizv.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableProizv.setFont(font)
        self.tableProizv.setMouseTracking(True)
        self.tableProizv.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableProizv.setAutoFillBackground(False)
        self.tableProizv.setStyleSheet("QTableWidget QTableCornerButton::section\n"
"{\n"
"    background: rgb(30, 30, 30);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    background: rgb(10, 10, 10);\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background: rgb(10, 10, 10);\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableProizv.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableProizv.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableProizv.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProizv.setShowGrid(False)
        self.tableProizv.setGridStyle(QtCore.Qt.SolidLine)
        self.tableProizv.setObjectName("tableProizv")
        self.tableProizv.setColumnCount(2)
        self.tableProizv.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProizv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProizv.setHorizontalHeaderItem(1, item)
        self.tableProizv.horizontalHeader().setVisible(False)
        self.tableProizv.horizontalHeader().setCascadingSectionResizes(True)
        self.tableProizv.horizontalHeader().setDefaultSectionSize(120)
        self.tableProizv.horizontalHeader().setHighlightSections(False)
        self.tableProizv.horizontalHeader().setMinimumSectionSize(15)
        self.tableProizv.horizontalHeader().setSortIndicatorShown(True)
        self.tableProizv.horizontalHeader().setStretchLastSection(False)
        self.tableProizv.verticalHeader().setVisible(False)
        self.tableProizv.verticalHeader().setCascadingSectionResizes(False)
        self.tableProizv.verticalHeader().setMinimumSectionSize(10)
        self.btnResetProizv = QtWidgets.QPushButton(self.frameProizv)
        self.btnResetProizv.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetProizv.setFont(font)
        self.btnResetProizv.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetProizv.setObjectName("btnResetProizv")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/up-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.toolBoxDiskFilter.addItem(self.proizvoditel, icon1, "")
        self.type = QtWidgets.QWidget()
        self.type.setGeometry(QtCore.QRect(0, 0, 307, 188))
        self.type.setObjectName("type")
        self.frameType = QtWidgets.QFrame(self.type)
        self.frameType.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.frameType.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameType.setObjectName("frameType")
        self.tableType = QtWidgets.QTableWidget(self.frameType)
        self.tableType.setEnabled(True)
        self.tableType.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableType.setFont(font)
        self.tableType.setMouseTracking(True)
        self.tableType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableType.setAutoFillBackground(False)
        self.tableType.setStyleSheet("QTableWidget QTableCornerButton::section\n"
"{\n"
"    \n"
"    background: rgb(30, 30, 30);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableType.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableType.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableType.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableType.setShowGrid(False)
        self.tableType.setGridStyle(QtCore.Qt.SolidLine)
        self.tableType.setObjectName("tableType")
        self.tableType.setColumnCount(2)
        self.tableType.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableType.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableType.setHorizontalHeaderItem(1, item)
        self.tableType.horizontalHeader().setVisible(False)
        self.tableType.horizontalHeader().setCascadingSectionResizes(True)
        self.tableType.horizontalHeader().setDefaultSectionSize(120)
        self.tableType.horizontalHeader().setHighlightSections(False)
        self.tableType.horizontalHeader().setMinimumSectionSize(15)
        self.tableType.horizontalHeader().setSortIndicatorShown(True)
        self.tableType.horizontalHeader().setStretchLastSection(False)
        self.tableType.verticalHeader().setVisible(False)
        self.tableType.verticalHeader().setCascadingSectionResizes(False)
        self.tableType.verticalHeader().setMinimumSectionSize(10)
        self.btnResetType = QtWidgets.QPushButton(self.frameType)
        self.btnResetType.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetType.setFont(font)
        self.btnResetType.setStyleSheet("QPushButton\n"
"{    \n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetType.setObjectName("btnResetType")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\filter\\../../images/down-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBoxDiskFilter.addItem(self.type, icon2, "")
        self.volume = QtWidgets.QWidget()
        self.volume.setGeometry(QtCore.QRect(0, 0, 307, 188))
        self.volume.setObjectName("volume")
        self.tbFrameVolume = QtWidgets.QFrame(self.volume)
        self.tbFrameVolume.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.tbFrameVolume.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}")
        self.tbFrameVolume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbFrameVolume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbFrameVolume.setObjectName("tbFrameVolume")
        self.sliderVolumeMin = QtWidgets.QSlider(self.tbFrameVolume)
        self.sliderVolumeMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderVolumeMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderVolumeMin.setProperty("value", 0)
        self.sliderVolumeMin.setTracking(True)
        self.sliderVolumeMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVolumeMin.setInvertedAppearance(False)
        self.sliderVolumeMin.setInvertedControls(False)
        self.sliderVolumeMin.setObjectName("sliderVolumeMin")
        self.line_4 = QtWidgets.QFrame(self.tbFrameVolume)
        self.line_4.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_4.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.sliderVolumeMax = QtWidgets.QSlider(self.tbFrameVolume)
        self.sliderVolumeMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderVolumeMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderVolumeMax.setProperty("value", 0)
        self.sliderVolumeMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVolumeMax.setInvertedAppearance(False)
        self.sliderVolumeMax.setInvertedControls(False)
        self.sliderVolumeMax.setObjectName("sliderVolumeMax")
        self.btnResetVolume = QtWidgets.QPushButton(self.tbFrameVolume)
        self.btnResetVolume.setGeometry(QtCore.QRect(220, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetVolume.setFont(font)
        self.btnResetVolume.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetVolume.setObjectName("btnResetVolume")
        self.lbMinVolume = QtWidgets.QLabel(self.tbFrameVolume)
        self.lbMinVolume.setGeometry(QtCore.QRect(10, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinVolume.setFont(font)
        self.lbMinVolume.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinVolume.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinVolume.setObjectName("lbMinVolume")
        self.lbMaxVolume = QtWidgets.QLabel(self.tbFrameVolume)
        self.lbMaxVolume.setGeometry(QtCore.QRect(180, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxVolume.setFont(font)
        self.lbMaxVolume.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxVolume.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxVolume.setObjectName("lbMaxVolume")
        self.leMinVolume = QtWidgets.QLineEdit(self.tbFrameVolume)
        self.leMinVolume.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinVolume.setFont(font)
        self.leMinVolume.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinVolume.setObjectName("leMinVolume")
        self.leMaxVolume = QtWidgets.QLineEdit(self.tbFrameVolume)
        self.leMaxVolume.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxVolume.setFont(font)
        self.leMaxVolume.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxVolume.setObjectName("leMaxVolume")
        self.toolBoxDiskFilter.addItem(self.volume, icon2, "")
        self.read = QtWidgets.QWidget()
        self.read.setGeometry(QtCore.QRect(0, 0, 307, 188))
        self.read.setObjectName("read")
        self.tbFrameRead = QtWidgets.QFrame(self.read)
        self.tbFrameRead.setGeometry(QtCore.QRect(0, -10, 311, 191))
        self.tbFrameRead.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}")
        self.tbFrameRead.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbFrameRead.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbFrameRead.setObjectName("tbFrameRead")
        self.sliderReadMin = QtWidgets.QSlider(self.tbFrameRead)
        self.sliderReadMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderReadMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderReadMin.setProperty("value", 0)
        self.sliderReadMin.setTracking(True)
        self.sliderReadMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderReadMin.setInvertedAppearance(False)
        self.sliderReadMin.setInvertedControls(False)
        self.sliderReadMin.setObjectName("sliderReadMin")
        self.line_6 = QtWidgets.QFrame(self.tbFrameRead)
        self.line_6.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_6.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.sliderReadMax = QtWidgets.QSlider(self.tbFrameRead)
        self.sliderReadMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderReadMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderReadMax.setProperty("value", 0)
        self.sliderReadMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderReadMax.setInvertedAppearance(False)
        self.sliderReadMax.setInvertedControls(False)
        self.sliderReadMax.setObjectName("sliderReadMax")
        self.btnResetVolume_3 = QtWidgets.QPushButton(self.tbFrameRead)
        self.btnResetVolume_3.setGeometry(QtCore.QRect(220, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetVolume_3.setFont(font)
        self.btnResetVolume_3.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetVolume_3.setObjectName("btnResetVolume_3")
        self.lbMinRead = QtWidgets.QLabel(self.tbFrameRead)
        self.lbMinRead.setGeometry(QtCore.QRect(10, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinRead.setFont(font)
        self.lbMinRead.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinRead.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinRead.setObjectName("lbMinRead")
        self.lbMaxRead = QtWidgets.QLabel(self.tbFrameRead)
        self.lbMaxRead.setGeometry(QtCore.QRect(180, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxRead.setFont(font)
        self.lbMaxRead.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxRead.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxRead.setObjectName("lbMaxRead")
        self.leMinRead = QtWidgets.QLineEdit(self.tbFrameRead)
        self.leMinRead.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinRead.setFont(font)
        self.leMinRead.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinRead.setObjectName("leMinRead")
        self.leMaxRead = QtWidgets.QLineEdit(self.tbFrameRead)
        self.leMaxRead.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxRead.setFont(font)
        self.leMaxRead.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxRead.setObjectName("leMaxRead")
        self.toolBoxDiskFilter.addItem(self.read, icon2, "")
        self.write = QtWidgets.QWidget()
        self.write.setGeometry(QtCore.QRect(0, 0, 307, 188))
        self.write.setObjectName("write")
        self.tbFrameWrite = QtWidgets.QFrame(self.write)
        self.tbFrameWrite.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.tbFrameWrite.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}")
        self.tbFrameWrite.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbFrameWrite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbFrameWrite.setObjectName("tbFrameWrite")
        self.sliderWriteMin = QtWidgets.QSlider(self.tbFrameWrite)
        self.sliderWriteMin.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.sliderWriteMin.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderWriteMin.setProperty("value", 0)
        self.sliderWriteMin.setTracking(True)
        self.sliderWriteMin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderWriteMin.setInvertedAppearance(False)
        self.sliderWriteMin.setInvertedControls(False)
        self.sliderWriteMin.setObjectName("sliderWriteMin")
        self.line_8 = QtWidgets.QFrame(self.tbFrameWrite)
        self.line_8.setGeometry(QtCore.QRect(140, 70, 21, 19))
        self.line_8.setStyleSheet("border:0px;\n"
"border-top: 1px solid white;")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.sliderWriteMax = QtWidgets.QSlider(self.tbFrameWrite)
        self.sliderWriteMax.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.sliderWriteMax.setStyleSheet("QSlider{\n"
"    background-color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: rgb(160,160,160);\n"
"height:6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.125 rgba(66, 68, 68, 255), stop:0.426136 rgba(117, 19, 19, 255), stop:0.852273 rgba(255, 0, 0, 255));\n"
"\n"
"color: rgb(144, 144, 144);\n"
"height: 6px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"border: 1px solid rgb(75,75,75);\n"
"background: rgb(70,70,70);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"border: 1px solid rgb(60,60,60);\n"
"background:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.057, stop:0 rgba(255, 0, 0, 255), stop:0.398876 rgba(165, 0, 0, 255), stop:0.994318 rgba(46, 48, 49, 255));\n"
"width: 6px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"border: 1px solid rgb(60,60,60);\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgb(105,105,105), stop:1 rgb(250,0,0));\n"
"width: 9px;\n"
"margin-top: -7px;\n"
"margin-bottom: -7px;\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sliderWriteMax.setProperty("value", 0)
        self.sliderWriteMax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderWriteMax.setInvertedAppearance(False)
        self.sliderWriteMax.setInvertedControls(False)
        self.sliderWriteMax.setObjectName("sliderWriteMax")
        self.btnResetWrite = QtWidgets.QPushButton(self.tbFrameWrite)
        self.btnResetWrite.setGeometry(QtCore.QRect(220, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetWrite.setFont(font)
        self.btnResetWrite.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetWrite.setObjectName("btnResetWrite")
        self.lbMinWrite = QtWidgets.QLabel(self.tbFrameWrite)
        self.lbMinWrite.setGeometry(QtCore.QRect(10, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMinWrite.setFont(font)
        self.lbMinWrite.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMinWrite.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinWrite.setObjectName("lbMinWrite")
        self.lbMaxWrite = QtWidgets.QLabel(self.tbFrameWrite)
        self.lbMaxWrite.setGeometry(QtCore.QRect(180, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMaxWrite.setFont(font)
        self.lbMaxWrite.setStyleSheet("    color: #fffafa;\n"
"    border: 0px;\n"
"")
        self.lbMaxWrite.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMaxWrite.setObjectName("lbMaxWrite")
        self.leMinWrite = QtWidgets.QLineEdit(self.tbFrameWrite)
        self.leMinWrite.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMinWrite.setFont(font)
        self.leMinWrite.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMinWrite.setObjectName("leMinWrite")
        self.leMaxWrite = QtWidgets.QLineEdit(self.tbFrameWrite)
        self.leMaxWrite.setGeometry(QtCore.QRect(180, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leMaxWrite.setFont(font)
        self.leMaxWrite.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leMaxWrite.setObjectName("leMaxWrite")
        self.toolBoxDiskFilter.addItem(self.write, icon2, "")
        self.rpm = QtWidgets.QWidget()
        self.rpm.setGeometry(QtCore.QRect(0, 0, 307, 188))
        self.rpm.setObjectName("rpm")
        self.frameRpm = QtWidgets.QFrame(self.rpm)
        self.frameRpm.setGeometry(QtCore.QRect(0, -10, 311, 191))
        self.frameRpm.setStyleSheet("QFrame{\n"
"    background-color: #101010;\n"
"}\n"
"")
        self.frameRpm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRpm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRpm.setObjectName("frameRpm")
        self.tableRpm = QtWidgets.QTableWidget(self.frameRpm)
        self.tableRpm.setEnabled(True)
        self.tableRpm.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableRpm.setFont(font)
        self.tableRpm.setMouseTracking(True)
        self.tableRpm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableRpm.setAutoFillBackground(False)
        self.tableRpm.setStyleSheet("QTableWidget QTableCornerButton::section\n"
"{\n"
"    \n"
"    background: rgb(30, 30, 30);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"     border-bottom: 1px solid rgb(60,60,60); \n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-top:0px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    background-color: #101010;\n"
"    color: #dddddd;\n"
"    border-top: 0px;\n"
"    border-right: 0px;\n"
"    border-left: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}      \n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"     color: white;\n"
"    border-bottom: 1px solid rgb(180,180,180);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #151515;\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #151515;\n"
"    min-height: 30px;\n"
"    border-radius: 0px;\n"
"    border: 1px solid;\n"
"    border-right: 0px;\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(50,50,50);\n"
"    border-color: rgb(60,60,60);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid rgb(180, 0, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    background-color: #151515;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    border: 1px solid;\n"
"    border-color: rgb(60,60,60);\n"
"    border: 1px solid;\n"
"    border-top:1px solid rgb(180, 0, 0);\n"
"    border-right: 0px;\n"
"    border-bottom: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: #575757;\n"
"    border-color: #242424;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(120, 0, 2);\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.tableRpm.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableRpm.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableRpm.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableRpm.setShowGrid(False)
        self.tableRpm.setGridStyle(QtCore.Qt.SolidLine)
        self.tableRpm.setObjectName("tableRpm")
        self.tableRpm.setColumnCount(2)
        self.tableRpm.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRpm.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRpm.setHorizontalHeaderItem(1, item)
        self.tableRpm.horizontalHeader().setVisible(False)
        self.tableRpm.horizontalHeader().setCascadingSectionResizes(True)
        self.tableRpm.horizontalHeader().setDefaultSectionSize(120)
        self.tableRpm.horizontalHeader().setHighlightSections(False)
        self.tableRpm.horizontalHeader().setMinimumSectionSize(15)
        self.tableRpm.horizontalHeader().setSortIndicatorShown(True)
        self.tableRpm.horizontalHeader().setStretchLastSection(False)
        self.tableRpm.verticalHeader().setVisible(False)
        self.tableRpm.verticalHeader().setCascadingSectionResizes(False)
        self.tableRpm.verticalHeader().setMinimumSectionSize(10)
        self.btnResetRpm = QtWidgets.QPushButton(self.frameRpm)
        self.btnResetRpm.setGeometry(QtCore.QRect(220, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.btnResetRpm.setFont(font)
        self.btnResetRpm.setStyleSheet("QPushButton\n"
"{    \n"
"    background-color: rgb(10, 10, 10);\n"
"    color:  rgb(200,200, 200);\n"
"    border: 0px;\n"
"    border-bottom: 1px dotted rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    color: red;\n"
"    border-bottom: 1px dotted red;\n"
"}\n"
"")
        self.btnResetRpm.setObjectName("btnResetRpm")
        self.toolBoxDiskFilter.addItem(self.rpm, icon2, "")

        self.retranslateUi(WidgetDiskFilter)
        self.toolBoxDiskFilter.layout().setSpacing(6)
        self.btnClose.clicked.connect(WidgetDiskFilter.close)
        QtCore.QMetaObject.connectSlotsByName(WidgetDiskFilter)

    def retranslateUi(self, WidgetDiskFilter):
        _translate = QtCore.QCoreApplication.translate
        WidgetDiskFilter.setWindowTitle(_translate("WidgetDiskFilter", "Form"))
        self.btnAccept.setText(_translate("WidgetDiskFilter", "Применить"))
        self.btnClose.setText(_translate("WidgetDiskFilter", "Отмена"))
        self.lbFilter.setText(_translate("WidgetDiskFilter", "Настройка фильтров"))
        self.btnResetAll.setText(_translate("WidgetDiskFilter", "Сбросить всё"))
        self.btnResetPrice.setText(_translate("WidgetDiskFilter", "Сбросить"))
        self.lbMinPrice.setText(_translate("WidgetDiskFilter", "мин., ₽:"))
        self.lbMaxPrice.setText(_translate("WidgetDiskFilter", "макс., ₽:"))
        self.leMinPrice.setPlaceholderText(_translate("WidgetDiskFilter", "от 0"))
        self.leMaxPrice.setPlaceholderText(_translate("WidgetDiskFilter", "до 78499"))
        self.toolBoxDiskFilter.setItemText(self.toolBoxDiskFilter.indexOf(self.price), _translate("WidgetDiskFilter", "Цена, ₽"))
        self.tableProizv.setSortingEnabled(True)
        item = self.tableProizv.horizontalHeaderItem(0)
        item.setText(_translate("WidgetDiskFilter", "Выбор"))
        item = self.tableProizv.horizontalHeaderItem(1)
        item.setText(_translate("WidgetDiskFilter", "Название"))
        self.btnResetProizv.setText(_translate("WidgetDiskFilter", "Сбросить"))
        self.toolBoxDiskFilter.setItemText(self.toolBoxDiskFilter.indexOf(self.proizvoditel), _translate("WidgetDiskFilter", "Производитель накопителя"))
        self.tableType.setSortingEnabled(True)
        item = self.tableType.horizontalHeaderItem(0)
        item.setText(_translate("WidgetDiskFilter", "Выбор"))
        item = self.tableType.horizontalHeaderItem(1)
        item.setText(_translate("WidgetDiskFilter", "Название"))
        self.btnResetType.setText(_translate("WidgetDiskFilter", "Сбросить"))
        self.toolBoxDiskFilter.setItemText(self.toolBoxDiskFilter.indexOf(self.type), _translate("WidgetDiskFilter", "Тип накопителя"))
        self.btnResetVolume.setText(_translate("WidgetDiskFilter", "Сбросить"))
        self.lbMinVolume.setText(_translate("WidgetDiskFilter", "мин., Гб:"))
        self.lbMaxVolume.setText(_translate("WidgetDiskFilter", "макс., Гб:"))
        self.leMinVolume.setPlaceholderText(_translate("WidgetDiskFilter", "от 0"))
        self.leMaxVolume.setPlaceholderText(_translate("WidgetDiskFilter", "до 78499"))
        self.toolBoxDiskFilter.setItemText(self.toolBoxDiskFilter.indexOf(self.volume), _translate("WidgetDiskFilter", "Объём [Гб]"))
        self.btnResetVolume_3.setText(_translate("WidgetDiskFilter", "Сбросить"))
        self.lbMinRead.setText(_translate("WidgetDiskFilter", "мин., Мб:"))
        self.lbMaxRead.setText(_translate("WidgetDiskFilter", "макс., Мб:"))
        self.leMinRead.setPlaceholderText(_translate("WidgetDiskFilter", "от 0"))
        self.leMaxRead.setPlaceholderText(_translate("WidgetDiskFilter", "до 10000"))
        self.toolBoxDiskFilter.setItemText(self.toolBoxDiskFilter.indexOf(self.read), _translate("WidgetDiskFilter", "Скорость чтения [Мб]"))
        self.btnResetWrite.setText(_translate("WidgetDiskFilter", "Сбросить"))
        self.lbMinWrite.setText(_translate("WidgetDiskFilter", "мин., Мб:"))
        self.lbMaxWrite.setText(_translate("WidgetDiskFilter", "макс., Мб:"))
        self.leMinWrite.setPlaceholderText(_translate("WidgetDiskFilter", "от 0"))
        self.leMaxWrite.setPlaceholderText(_translate("WidgetDiskFilter", "до 10000"))
        self.toolBoxDiskFilter.setItemText(self.toolBoxDiskFilter.indexOf(self.write), _translate("WidgetDiskFilter", "Скорость записи [Мб]"))
        self.tableRpm.setSortingEnabled(True)
        item = self.tableRpm.horizontalHeaderItem(0)
        item.setText(_translate("WidgetDiskFilter", "Выбор"))
        item = self.tableRpm.horizontalHeaderItem(1)
        item.setText(_translate("WidgetDiskFilter", "Название"))
        self.btnResetRpm.setText(_translate("WidgetDiskFilter", "Сбросить"))
        self.toolBoxDiskFilter.setItemText(self.toolBoxDiskFilter.indexOf(self.rpm), _translate("WidgetDiskFilter", "Скорость об.\\мин. (RPM)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetDiskFilter = QtWidgets.QWidget()
    ui = Ui_WidgetDiskFilter()
    ui.setupUi(WidgetDiskFilter)
    WidgetDiskFilter.show()
    sys.exit(app.exec_())
