# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\help\widgetCoolHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetCoolHelp(object):
    def setupUi(self, widgetCoolHelp):
        widgetCoolHelp.setObjectName("widgetCoolHelp")
        widgetCoolHelp.resize(893, 729)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\help\\../../images/faq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widgetCoolHelp.setWindowIcon(icon)
        widgetCoolHelp.setStyleSheet("QWidget{\n"
"    background-color: rgb(30,30,30);\n"
"    color: white;\n"
"}")
        self.line_2 = QtWidgets.QFrame(widgetCoolHelp)
        self.line_2.setGeometry(QtCore.QRect(10, 170, 20, 171))
        self.line_2.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.rectangle = QtWidgets.QFrame(widgetCoolHelp)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.lbHowVidTxt_2 = QtWidgets.QLabel(widgetCoolHelp)
        self.lbHowVidTxt_2.setGeometry(QtCore.QRect(40, 170, 821, 171))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.lbHowVidTxt_2.setFont(font)
        self.lbHowVidTxt_2.setStyleSheet("color: rgb(220,220,220);")
        self.lbHowVidTxt_2.setTextFormat(QtCore.Qt.PlainText)
        self.lbHowVidTxt_2.setScaledContents(False)
        self.lbHowVidTxt_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbHowVidTxt_2.setWordWrap(True)
        self.lbHowVidTxt_2.setOpenExternalLinks(False)
        self.lbHowVidTxt_2.setObjectName("lbHowVidTxt_2")
        self.lbHowVidTxt = QtWidgets.QLabel(widgetCoolHelp)
        self.lbHowVidTxt.setGeometry(QtCore.QRect(40, 80, 821, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.lbHowVidTxt.setFont(font)
        self.lbHowVidTxt.setStyleSheet("color: rgb(220,220,220);")
        self.lbHowVidTxt.setTextFormat(QtCore.Qt.PlainText)
        self.lbHowVidTxt.setScaledContents(False)
        self.lbHowVidTxt.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbHowVidTxt.setWordWrap(True)
        self.lbHowVidTxt.setOpenExternalLinks(False)
        self.lbHowVidTxt.setObjectName("lbHowVidTxt")
        self.line_4 = QtWidgets.QFrame(widgetCoolHelp)
        self.line_4.setGeometry(QtCore.QRect(10, 80, 20, 61))
        self.line_4.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.btnClose = QtWidgets.QPushButton(widgetCoolHelp)
        self.btnClose.setGeometry(QtCore.QRect(390, 680, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(40,40,40);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnClose.setObjectName("btnClose")
        self.lbHowVid = QtWidgets.QLabel(widgetCoolHelp)
        self.lbHowVid.setGeometry(QtCore.QRect(40, 30, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.lbHowVid.setFont(font)
        self.lbHowVid.setObjectName("lbHowVid")
        self.line_3 = QtWidgets.QFrame(widgetCoolHelp)
        self.line_3.setGeometry(QtCore.QRect(460, 410, 20, 251))
        self.line_3.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lbGeForce = QtWidgets.QLabel(widgetCoolHelp)
        self.lbGeForce.setGeometry(QtCore.QRect(40, 410, 381, 251))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lbGeForce.setFont(font)
        self.lbGeForce.setAutoFillBackground(False)
        self.lbGeForce.setStyleSheet("color: rgb(220,220,220);")
        self.lbGeForce.setTextFormat(QtCore.Qt.PlainText)
        self.lbGeForce.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbGeForce.setWordWrap(True)
        self.lbGeForce.setObjectName("lbGeForce")
        self.lbAmd = QtWidgets.QLabel(widgetCoolHelp)
        self.lbAmd.setGeometry(QtCore.QRect(500, 360, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.lbAmd.setFont(font)
        self.lbAmd.setObjectName("lbAmd")
        self.lbNvidia = QtWidgets.QLabel(widgetCoolHelp)
        self.lbNvidia.setGeometry(QtCore.QRect(40, 360, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbNvidia.setFont(font)
        self.lbNvidia.setObjectName("lbNvidia")
        self.lbRadeon = QtWidgets.QLabel(widgetCoolHelp)
        self.lbRadeon.setGeometry(QtCore.QRect(490, 410, 381, 251))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lbRadeon.setFont(font)
        self.lbRadeon.setAutoFillBackground(False)
        self.lbRadeon.setStyleSheet("color: rgb(220,220,220);")
        self.lbRadeon.setTextFormat(QtCore.Qt.PlainText)
        self.lbRadeon.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbRadeon.setWordWrap(True)
        self.lbRadeon.setObjectName("lbRadeon")
        self.line = QtWidgets.QFrame(widgetCoolHelp)
        self.line.setGeometry(QtCore.QRect(10, 410, 20, 251))
        self.line.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(widgetCoolHelp)
        self.btnClose.clicked.connect(widgetCoolHelp.close)
        QtCore.QMetaObject.connectSlotsByName(widgetCoolHelp)

    def retranslateUi(self, widgetCoolHelp):
        _translate = QtCore.QCoreApplication.translate
        widgetCoolHelp.setWindowTitle(_translate("widgetCoolHelp", "Подобрать охлаждение"))
        self.lbHowVidTxt_2.setText(_translate("widgetCoolHelp", "При выборе кулера следует обратить внимание на такие параметры, как: \n"
"-рассеиваемость тепла кулером, \n"
"-габариты кулера для размещения внутри компьютера, \n"
"-тип кулера или охлаждения: \n"
"  башенный - с наибольшим КПД но большими габаритами; \n"
"  горизонтальный - с не таким большим КПД, но очень компактными размерами; \n"
"  смешанный - симбиоз башенного и горизонтального; \n"
"  водяное - охлаждение с использованием жидкости (наиболее эффективны)."))
        self.lbHowVidTxt.setText(_translate("widgetCoolHelp", "Кулер - система охлаждения процессора, состоящая алюминиевого либо медного радиатора и обдувающего его вентилятора. Задача устройства – снижение нагрева комплектующих и, таким образом, повышение эффективности работы компьютера."))
        self.btnClose.setText(_translate("widgetCoolHelp", "Закрыть"))
        self.lbHowVid.setText(_translate("widgetCoolHelp", "Как подобрать охлаждение процессора?"))
        self.lbGeForce.setText(_translate("widgetCoolHelp", "Воздушное охлаждение самое популярное на данный момент из-за относительно низкой цены, простоты установки и обслуживания, а также максимальной надежности, ведь сломаться может разве что вентилятор, который очень легко заменить.\n"
"Связка радиатора с вентилятором обычно называется кулером. А самыми эффективными для охлаждения центрального процессора являются кулеры башенной конструкции с тепловыми трубками. Радиатор состоит из медного основания, которое контактирует с крышкой процессора, передающей тепло процессора кулеру. "))
        self.lbAmd.setText(_translate("widgetCoolHelp", "Жидкостное охлаждение"))
        self.lbNvidia.setText(_translate("widgetCoolHelp", "Воздушное охлаждение"))
        self.lbRadeon.setText(_translate("widgetCoolHelp", "Их принцип работы также состоит в передаче тепла на радиатор, но это происходит при помощи рабочей жидкости (обычно смесь дистиллированной воды и различных присадок от коррозии и бактерий), которая циркулирует в замкнутом контуре по специальным трубкам. Это выгодно отличает водяное охлаждение, поскольку жидкость имеет гораздо большую теплоемкость и теплопроводность, что позволяет отвести больше энергии за единицу времени.\n"
"Однако такие системы стоят намного дороже, а удобство закрытой системы может стать минусом, ведь невозможно прочистить водоблок или поменять вышедшую из строя помпу."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widgetCoolHelp = QtWidgets.QWidget()
    ui = Ui_widgetCoolHelp()
    ui.setupUi(widgetCoolHelp)
    widgetCoolHelp.show()
    sys.exit(app.exec_())
