# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\help\widgetPowerHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetPowerHelp(object):
    def setupUi(self, widgetPowerHelp):
        widgetPowerHelp.setObjectName("widgetPowerHelp")
        widgetPowerHelp.resize(910, 368)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\help\\../../images/faq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widgetPowerHelp.setWindowIcon(icon)
        widgetPowerHelp.setStyleSheet("QWidget{\n"
"    background-color: rgb(30,30,30);\n"
"    color: white;\n"
"}")
        self.btnClose = QtWidgets.QPushButton(widgetPowerHelp)
        self.btnClose.setGeometry(QtCore.QRect(370, 320, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(40,40,40);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnClose.setObjectName("btnClose")
        self.lbHowVidTxt_2 = QtWidgets.QLabel(widgetPowerHelp)
        self.lbHowVidTxt_2.setGeometry(QtCore.QRect(40, 230, 821, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.lbHowVidTxt_2.setFont(font)
        self.lbHowVidTxt_2.setStyleSheet("color: rgb(220,220,220);")
        self.lbHowVidTxt_2.setTextFormat(QtCore.Qt.PlainText)
        self.lbHowVidTxt_2.setScaledContents(False)
        self.lbHowVidTxt_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbHowVidTxt_2.setWordWrap(True)
        self.lbHowVidTxt_2.setOpenExternalLinks(False)
        self.lbHowVidTxt_2.setObjectName("lbHowVidTxt_2")
        self.lbHowVid = QtWidgets.QLabel(widgetPowerHelp)
        self.lbHowVid.setGeometry(QtCore.QRect(40, 30, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.lbHowVid.setFont(font)
        self.lbHowVid.setObjectName("lbHowVid")
        self.line_2 = QtWidgets.QFrame(widgetPowerHelp)
        self.line_2.setGeometry(QtCore.QRect(10, 230, 20, 61))
        self.line_2.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lbHowVidTxt = QtWidgets.QLabel(widgetPowerHelp)
        self.lbHowVidTxt.setGeometry(QtCore.QRect(40, 80, 821, 131))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.lbHowVidTxt.setFont(font)
        self.lbHowVidTxt.setStyleSheet("color: rgb(220,220,220);")
        self.lbHowVidTxt.setTextFormat(QtCore.Qt.PlainText)
        self.lbHowVidTxt.setScaledContents(False)
        self.lbHowVidTxt.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbHowVidTxt.setWordWrap(True)
        self.lbHowVidTxt.setOpenExternalLinks(False)
        self.lbHowVidTxt.setObjectName("lbHowVidTxt")
        self.rectangle = QtWidgets.QFrame(widgetPowerHelp)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.line_4 = QtWidgets.QFrame(widgetPowerHelp)
        self.line_4.setGeometry(QtCore.QRect(10, 80, 20, 121))
        self.line_4.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.retranslateUi(widgetPowerHelp)
        self.btnClose.clicked.connect(widgetPowerHelp.close)
        QtCore.QMetaObject.connectSlotsByName(widgetPowerHelp)

    def retranslateUi(self, widgetPowerHelp):
        _translate = QtCore.QCoreApplication.translate
        widgetPowerHelp.setWindowTitle(_translate("widgetPowerHelp", "Подобрать блок питания"))
        self.btnClose.setText(_translate("widgetPowerHelp", "Закрыть"))
        self.lbHowVidTxt_2.setText(_translate("widgetPowerHelp", "При выборе блока питания следует обращать внимание на наличие сертификата 80plus, который отражает энергоэффективность(КПД) блока не менее 80%;  на его габариты, а также общую мощность, которая должна составлять 50-80% загруженности блока питания."))
        self.lbHowVid.setText(_translate("widgetPowerHelp", "Как подобрать блок питания?"))
        self.lbHowVidTxt.setText(_translate("widgetPowerHelp", "Блок питания – это устройство, которое используется для создания напряжения, необходимого для работы компьютера, из напряжения домашней электросети.\n"
"БП преобразовывает переменный ток из сети электропитания в постоянный, понижает напряжение тока с 110-230 В до требуемых компонентами ПК 12, 5 и 3,3 В и стабилизирует напряжения. Именно БП должен обеспечивать стабильную работу и отвечать за безопасность железа при скачках и перебоях в сети."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widgetPowerHelp = QtWidgets.QWidget()
    ui = Ui_widgetPowerHelp()
    ui.setupUi(widgetPowerHelp)
    widgetPowerHelp.show()
    sys.exit(app.exec_())
