# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\help\widgetProcHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetProcHelp(object):
    def setupUi(self, widgetProcHelp):
        widgetProcHelp.setObjectName("widgetProcHelp")
        widgetProcHelp.resize(897, 646)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\help\\../../images/faq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widgetProcHelp.setWindowIcon(icon)
        widgetProcHelp.setStyleSheet("QWidget{\n"
"    background-color: rgb(30,30,30);\n"
"    color: white;\n"
"}")
        self.line_3 = QtWidgets.QFrame(widgetProcHelp)
        self.line_3.setGeometry(QtCore.QRect(460, 340, 20, 231))
        self.line_3.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lbHowVidTxt = QtWidgets.QLabel(widgetProcHelp)
        self.lbHowVidTxt.setGeometry(QtCore.QRect(40, 80, 821, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.lbHowVidTxt.setFont(font)
        self.lbHowVidTxt.setStyleSheet("color: rgb(220,220,220);")
        self.lbHowVidTxt.setTextFormat(QtCore.Qt.PlainText)
        self.lbHowVidTxt.setScaledContents(False)
        self.lbHowVidTxt.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbHowVidTxt.setWordWrap(True)
        self.lbHowVidTxt.setOpenExternalLinks(False)
        self.lbHowVidTxt.setObjectName("lbHowVidTxt")
        self.line_2 = QtWidgets.QFrame(widgetProcHelp)
        self.line_2.setGeometry(QtCore.QRect(10, 190, 20, 81))
        self.line_2.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lbHowVid = QtWidgets.QLabel(widgetProcHelp)
        self.lbHowVid.setGeometry(QtCore.QRect(40, 30, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.lbHowVid.setFont(font)
        self.lbHowVid.setObjectName("lbHowVid")
        self.lbGeForce = QtWidgets.QLabel(widgetProcHelp)
        self.lbGeForce.setGeometry(QtCore.QRect(40, 340, 381, 241))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lbGeForce.setFont(font)
        self.lbGeForce.setAutoFillBackground(False)
        self.lbGeForce.setStyleSheet("color: rgb(220,220,220);")
        self.lbGeForce.setTextFormat(QtCore.Qt.PlainText)
        self.lbGeForce.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbGeForce.setWordWrap(True)
        self.lbGeForce.setObjectName("lbGeForce")
        self.lbAmd = QtWidgets.QLabel(widgetProcHelp)
        self.lbAmd.setGeometry(QtCore.QRect(490, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.lbAmd.setFont(font)
        self.lbAmd.setObjectName("lbAmd")
        self.btnClose = QtWidgets.QPushButton(widgetProcHelp)
        self.btnClose.setGeometry(QtCore.QRect(390, 600, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(40,40,40);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnClose.setObjectName("btnClose")
        self.lbNvidia = QtWidgets.QLabel(widgetProcHelp)
        self.lbNvidia.setGeometry(QtCore.QRect(40, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbNvidia.setFont(font)
        self.lbNvidia.setObjectName("lbNvidia")
        self.line_4 = QtWidgets.QFrame(widgetProcHelp)
        self.line_4.setGeometry(QtCore.QRect(10, 80, 20, 81))
        self.line_4.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.rectangle = QtWidgets.QFrame(widgetProcHelp)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.lbRadeon = QtWidgets.QLabel(widgetProcHelp)
        self.lbRadeon.setGeometry(QtCore.QRect(490, 340, 381, 241))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lbRadeon.setFont(font)
        self.lbRadeon.setAutoFillBackground(False)
        self.lbRadeon.setStyleSheet("color: rgb(220,220,220);")
        self.lbRadeon.setTextFormat(QtCore.Qt.PlainText)
        self.lbRadeon.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbRadeon.setWordWrap(True)
        self.lbRadeon.setObjectName("lbRadeon")
        self.line = QtWidgets.QFrame(widgetProcHelp)
        self.line.setGeometry(QtCore.QRect(10, 340, 20, 181))
        self.line.setStyleSheet("border: 0px;\n"
"border-right: 1px solid rgb(210, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbHowVidTxt_2 = QtWidgets.QLabel(widgetProcHelp)
        self.lbHowVidTxt_2.setGeometry(QtCore.QRect(40, 190, 821, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.lbHowVidTxt_2.setFont(font)
        self.lbHowVidTxt_2.setStyleSheet("color: rgb(220,220,220);")
        self.lbHowVidTxt_2.setTextFormat(QtCore.Qt.PlainText)
        self.lbHowVidTxt_2.setScaledContents(False)
        self.lbHowVidTxt_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.lbHowVidTxt_2.setWordWrap(True)
        self.lbHowVidTxt_2.setOpenExternalLinks(False)
        self.lbHowVidTxt_2.setObjectName("lbHowVidTxt_2")

        self.retranslateUi(widgetProcHelp)
        self.btnClose.clicked.connect(widgetProcHelp.close)
        QtCore.QMetaObject.connectSlotsByName(widgetProcHelp)

    def retranslateUi(self, widgetProcHelp):
        _translate = QtCore.QCoreApplication.translate
        widgetProcHelp.setWindowTitle(_translate("widgetProcHelp", "Подобрать процессор"))
        self.lbHowVidTxt.setText(_translate("widgetProcHelp", "Центральный процессор (ЦП) – основной компонент компьютера, который выполняет арифметические и логические операции, заданные программой, управляет процессом вычислений и координирует работу всех устройств ПК. В большей степени от мощности процессора зависит скорость работы всего ПК."))
        self.lbHowVid.setText(_translate("widgetProcHelp", "Как подобрать процессор?"))
        self.lbGeForce.setText(_translate("widgetProcHelp", "Процессоры Intel Core делают упор производительность каждого конкретного ядра и лучше всего подходят под задачи, в которых не требуется большая многозадачность. В связи с этим повышается и надежность ядер, так что большинство вышедших из строя процессоров в сервисах по ремонту ПК являются продуктами от Amd, которые работают несколько иначе. \n"
"Также стоит отметить, что продукция Intel, как правило, дороже Amd."))
        self.lbAmd.setText(_translate("widgetProcHelp", "AMD Ryzen"))
        self.btnClose.setText(_translate("widgetProcHelp", "Закрыть"))
        self.lbNvidia.setText(_translate("widgetProcHelp", "Intel Core"))
        self.lbRadeon.setText(_translate("widgetProcHelp", "Процессоры от AMD жертвуют мощностью ядер ради расширенной многопоточности, благодаря чему появляется возможность обрабатывать гораздо больше процессов одновременно. Но, увы, если требуется обработать действительно весомый и многозадачный процесс, Amd Ryzen обычно уступает устройствам Intel.\n"
"Между тем, AMD отличаются от Intel намного более производительными внутренними графическими чипами, что позволяет собирать достаточно бюджетные решения без видеокарты. \n"
"Цена у AMD чаще всего ниже, особенно это заметно в среднем и бюджетном сегменте цен."))
        self.lbHowVidTxt_2.setText(_translate("widgetProcHelp", "При выборе процессора следует обратить внимание на такие параметры, как тактовая частота (количество выполняемых операций за 1 такт), количество ядер (многопоточность и разделение процессов) и семейство (часто семейство определяет ключевую производительность серии процессоров). Данные параметры в большей степени влияют на производительность ЦП."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widgetProcHelp = QtWidgets.QWidget()
    ui = Ui_widgetProcHelp()
    ui.setupUi(widgetProcHelp)
    widgetProcHelp.show()
    sys.exit(app.exec_())
