# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\add\addChRamWidg.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addChRamWidg(object):
    def setupUi(self, addChRamWidg):
        addChRamWidg.setObjectName("addChRamWidg")
        addChRamWidg.resize(878, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\add\\../../images/win_add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addChRamWidg.setWindowIcon(icon)
        addChRamWidg.setStyleSheet("QWidget\n"
"{\n"
"    background: rgb(30, 30, 30);\n"
"    color: white;\n"
"}\n"
"")
        self.leVoltage = QtWidgets.QLineEdit(addChRamWidg)
        self.leVoltage.setGeometry(QtCore.QRect(330, 380, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leVoltage.setFont(font)
        self.leVoltage.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leVoltage.setInputMask("")
        self.leVoltage.setPlaceholderText("")
        self.leVoltage.setObjectName("leVoltage")
        self.lbDate = QtWidgets.QLabel(addChRamWidg)
        self.lbDate.setGeometry(QtCore.QRect(670, 440, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbDate.setFont(font)
        self.lbDate.setStyleSheet("border:0px;")
        self.lbDate.setObjectName("lbDate")
        self.leKol = QtWidgets.QLineEdit(addChRamWidg)
        self.leKol.setGeometry(QtCore.QRect(20, 470, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leKol.setFont(font)
        self.leKol.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leKol.setInputMask("")
        self.leKol.setObjectName("leKol")
        self.line_3 = QtWidgets.QFrame(addChRamWidg)
        self.line_3.setGeometry(QtCore.QRect(20, 430, 841, 16))
        self.line_3.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lbVoltage = QtWidgets.QLabel(addChRamWidg)
        self.lbVoltage.setGeometry(QtCore.QRect(330, 350, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbVoltage.setFont(font)
        self.lbVoltage.setStyleSheet("border:0px;")
        self.lbVoltage.setObjectName("lbVoltage")
        self.leLatency = QtWidgets.QLineEdit(addChRamWidg)
        self.leLatency.setGeometry(QtCore.QRect(20, 380, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leLatency.setFont(font)
        self.leLatency.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leLatency.setInputMask("")
        self.leLatency.setPlaceholderText("")
        self.leLatency.setObjectName("leLatency")
        self.lbProcProizv = QtWidgets.QLabel(addChRamWidg)
        self.lbProcProizv.setGeometry(QtCore.QRect(20, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbProcProizv.setFont(font)
        self.lbProcProizv.setStyleSheet("border:0px;")
        self.lbProcProizv.setObjectName("lbProcProizv")
        self.cbProizv = QtWidgets.QComboBox(addChRamWidg)
        self.cbProizv.setGeometry(QtCore.QRect(20, 120, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbProizv.setFont(font)
        self.cbProizv.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbProizv.setEditable(False)
        self.cbProizv.setIconSize(QtCore.QSize(20, 20))
        self.cbProizv.setDuplicatesEnabled(False)
        self.cbProizv.setFrame(False)
        self.cbProizv.setModelColumn(0)
        self.cbProizv.setObjectName("cbProizv")
        self.cbProizv.addItem("")
        self.line_2 = QtWidgets.QFrame(addChRamWidg)
        self.line_2.setGeometry(QtCore.QRect(20, 330, 841, 16))
        self.line_2.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dateEdit = QtWidgets.QDateEdit(addChRamWidg)
        self.dateEdit.setGeometry(QtCore.QRect(670, 470, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"}\n"
"QDateEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"QDateEdit::drop-down{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"    border: 2px solid rgb(100,0,0)\n"
"}\n"
"\n"
"QDateEdit:on{\n"
"    border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QDateEdit::up-arrow {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar { background-color: rgb(40,40,40); }\n"
"QCalendarWidget QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 70px;\n"
"    height: 25px;\n"
"    color: rgb(220,220,220);\n"
"    font-size: 14px;\n"
"    icon-size: 30px, 30px;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth {\n"
"    background: rgb(45,45,45);\n"
"    border: none;\n"
"    width: 30px;\n"
"    height: 25px;\n"
"    qproperty-icon:  url(\"E:/pcconf/images/left-arrow.png\");\n"
"    icon-size: 20px, 20px;\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"QToolButton#qt_calendar_nextmonth {\n"
"    background: rgb(35,35,35);\n"
"    border: none;\n"
"    width: 30px;\n"
"    height: 25px;\n"
"    qproperty-icon:  url(\"E:/pcconf/images/right-arrow.png\");\n"
"    icon-size: 20px, 20px;\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    width: 100px;\n"
"    left: 10px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    selection-color: rgb(220,0,0);\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox { \n"
"    width: 45px; \n"
"    font-size:14px; \n"
"    color: white; \n"
"    background: transparent;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"QCalendarWidget QSpinBox::up-button { subcontrol-origin: border;  subcontrol-position: top right;  width:15px; height: 15px; border:1px solid rgb(30,30,30); }\n"
"QCalendarWidget QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right;  width:15px;  height: 15px; border:1px solid rgb(30,30,30);}\n"
"QCalendarWidget QSpinBox::up-arrow { border-image: url(\"E:/pcconf/images/up-arrow.png\"); }\n"
"QCalendarWidget QSpinBox::down-arrow { border-image: url(\"E:/pcconf/images/down-arrow.png\");}\n"
" \n"
"/* header row */\n"
"QCalendarWidget QWidget { alternate-background-color: rgb(50, 50, 50);  border-bottom: 1px solid red; }\n"
" \n"
"/* normal days */\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    font-size:12px;  \n"
"    color: rgb(180, 180, 180);  \n"
"    background-color: rgb(15, 15, 15);  \n"
"    selection-background-color: rgb(64, 64, 64); \n"
"    selection-color: rgb(0, 255, 0); \n"
"    selection-border-color: red;\n"
"    height: 30px;\n"
"}\n"
" \n"
"/* days in other months */\n"
"QCalendarWidget QAbstractItemView:disabled { color: rgb(80, 80, 80); }")
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.lbKol = QtWidgets.QLabel(addChRamWidg)
        self.lbKol.setGeometry(QtCore.QRect(20, 440, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbKol.setFont(font)
        self.lbKol.setStyleSheet("border:0px;")
        self.lbKol.setObjectName("lbKol")
        self.lbPrice = QtWidgets.QLabel(addChRamWidg)
        self.lbPrice.setGeometry(QtCore.QRect(170, 440, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbPrice.setFont(font)
        self.lbPrice.setStyleSheet("border:0px;")
        self.lbPrice.setObjectName("lbPrice")
        self.lbVolume = QtWidgets.QLabel(addChRamWidg)
        self.lbVolume.setGeometry(QtCore.QRect(330, 250, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbVolume.setFont(font)
        self.lbVolume.setStyleSheet("border:0px;")
        self.lbVolume.setObjectName("lbVolume")
        self.lbComplect = QtWidgets.QLabel(addChRamWidg)
        self.lbComplect.setGeometry(QtCore.QRect(680, 40, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        self.lbComplect.setFont(font)
        self.lbComplect.setStyleSheet("border:0px;")
        self.lbComplect.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbComplect.setObjectName("lbComplect")
        self.lbLatency = QtWidgets.QLabel(addChRamWidg)
        self.lbLatency.setGeometry(QtCore.QRect(20, 350, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbLatency.setFont(font)
        self.lbLatency.setStyleSheet("border:0px;")
        self.lbLatency.setObjectName("lbLatency")
        self.rectangle = QtWidgets.QFrame(addChRamWidg)
        self.rectangle.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.lbProcGaming = QtWidgets.QLabel(addChRamWidg)
        self.lbProcGaming.setGeometry(QtCore.QRect(500, 90, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbProcGaming.setFont(font)
        self.lbProcGaming.setStyleSheet("border:0px;")
        self.lbProcGaming.setObjectName("lbProcGaming")
        self.line = QtWidgets.QFrame(addChRamWidg)
        self.line.setGeometry(QtCore.QRect(20, 70, 841, 16))
        self.line.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnSave = QtWidgets.QPushButton(addChRamWidg)
        self.btnSave.setGeometry(QtCore.QRect(250, 550, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-bottom: 1px solid rgb(0, 255, 8);\n"
"}\n"
"")
        self.btnSave.setObjectName("btnSave")
        self.leFullName = QtWidgets.QLineEdit(addChRamWidg)
        self.leFullName.setGeometry(QtCore.QRect(20, 200, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leFullName.setFont(font)
        self.leFullName.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leFullName.setObjectName("leFullName")
        self.btnCancel = QtWidgets.QPushButton(addChRamWidg)
        self.btnCancel.setGeometry(QtCore.QRect(440, 550, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setDefault(False)
        self.btnCancel.setFlat(False)
        self.btnCancel.setObjectName("btnCancel")
        self.lePrice = QtWidgets.QLineEdit(addChRamWidg)
        self.lePrice.setGeometry(QtCore.QRect(170, 470, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lePrice.setFont(font)
        self.lePrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.lePrice.setInputMask("")
        self.lePrice.setObjectName("lePrice")
        self.line_4 = QtWidgets.QFrame(addChRamWidg)
        self.line_4.setGeometry(QtCore.QRect(20, 520, 841, 16))
        self.line_4.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lbFullName = QtWidgets.QLabel(addChRamWidg)
        self.lbFullName.setGeometry(QtCore.QRect(20, 170, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbFullName.setFont(font)
        self.lbFullName.setStyleSheet("")
        self.lbFullName.setObjectName("lbFullName")
        self.cbGaming = QtWidgets.QComboBox(addChRamWidg)
        self.cbGaming.setGeometry(QtCore.QRect(500, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbGaming.setFont(font)
        self.cbGaming.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbGaming.setEditable(False)
        self.cbGaming.setIconSize(QtCore.QSize(20, 20))
        self.cbGaming.setDuplicatesEnabled(False)
        self.cbGaming.setFrame(False)
        self.cbGaming.setModelColumn(0)
        self.cbGaming.setObjectName("cbGaming")
        self.cbGaming.addItem("")
        self.cbGaming.addItem("")
        self.lbRamType = QtWidgets.QLabel(addChRamWidg)
        self.lbRamType.setGeometry(QtCore.QRect(20, 250, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbRamType.setFont(font)
        self.lbRamType.setStyleSheet("border:0px;")
        self.lbRamType.setObjectName("lbRamType")
        self.cbRamType = QtWidgets.QComboBox(addChRamWidg)
        self.cbRamType.setGeometry(QtCore.QRect(20, 280, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbRamType.setFont(font)
        self.cbRamType.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbRamType.setEditable(False)
        self.cbRamType.setIconSize(QtCore.QSize(20, 20))
        self.cbRamType.setDuplicatesEnabled(False)
        self.cbRamType.setFrame(False)
        self.cbRamType.setModelColumn(0)
        self.cbRamType.setObjectName("cbRamType")
        self.cbRamType.addItem("")
        self.cbRamType.addItem("")
        self.cbRamType.addItem("")
        self.cbRamType.addItem("")
        self.cbRamType.addItem("")
        self.lbFreq = QtWidgets.QLabel(addChRamWidg)
        self.lbFreq.setGeometry(QtCore.QRect(330, 170, 191, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbFreq.setFont(font)
        self.lbFreq.setStyleSheet("border:0px;")
        self.lbFreq.setObjectName("lbFreq")
        self.leFreq = QtWidgets.QLineEdit(addChRamWidg)
        self.leFreq.setGeometry(QtCore.QRect(330, 200, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leFreq.setFont(font)
        self.leFreq.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leFreq.setInputMask("")
        self.leFreq.setObjectName("leFreq")
        self.cbModule = QtWidgets.QComboBox(addChRamWidg)
        self.cbModule.setGeometry(QtCore.QRect(170, 280, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbModule.setFont(font)
        self.cbModule.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbModule.setEditable(False)
        self.cbModule.setIconSize(QtCore.QSize(20, 20))
        self.cbModule.setDuplicatesEnabled(False)
        self.cbModule.setFrame(False)
        self.cbModule.setModelColumn(0)
        self.cbModule.setObjectName("cbModule")
        self.cbModule.addItem("")
        self.cbModule.addItem("")
        self.cbModule.addItem("")
        self.cbModule.addItem("")
        self.lbModule = QtWidgets.QLabel(addChRamWidg)
        self.lbModule.setGeometry(QtCore.QRect(170, 250, 161, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbModule.setFont(font)
        self.lbModule.setStyleSheet("border:0px;")
        self.lbModule.setObjectName("lbModule")
        self.cbVolume = QtWidgets.QComboBox(addChRamWidg)
        self.cbVolume.setGeometry(QtCore.QRect(330, 280, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbVolume.setFont(font)
        self.cbVolume.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbVolume.setEditable(False)
        self.cbVolume.setIconSize(QtCore.QSize(20, 20))
        self.cbVolume.setDuplicatesEnabled(False)
        self.cbVolume.setFrame(False)
        self.cbVolume.setModelColumn(0)
        self.cbVolume.setObjectName("cbVolume")
        self.cbVolume.addItem("")
        self.cbVolume.addItem("")
        self.cbVolume.addItem("")
        self.cbVolume.addItem("")
        self.cbVolume.addItem("")
        self.cbVolume.addItem("")
        self.lbModule.raise_()
        self.leVoltage.raise_()
        self.lbDate.raise_()
        self.leKol.raise_()
        self.line_3.raise_()
        self.lbVoltage.raise_()
        self.leLatency.raise_()
        self.lbProcProizv.raise_()
        self.cbProizv.raise_()
        self.line_2.raise_()
        self.dateEdit.raise_()
        self.lbKol.raise_()
        self.lbPrice.raise_()
        self.lbVolume.raise_()
        self.lbComplect.raise_()
        self.lbLatency.raise_()
        self.rectangle.raise_()
        self.lbProcGaming.raise_()
        self.line.raise_()
        self.btnSave.raise_()
        self.leFullName.raise_()
        self.btnCancel.raise_()
        self.lePrice.raise_()
        self.line_4.raise_()
        self.lbFullName.raise_()
        self.cbGaming.raise_()
        self.lbRamType.raise_()
        self.cbRamType.raise_()
        self.lbFreq.raise_()
        self.leFreq.raise_()
        self.cbModule.raise_()
        self.cbVolume.raise_()

        self.retranslateUi(addChRamWidg)
        self.btnCancel.clicked.connect(addChRamWidg.close)
        QtCore.QMetaObject.connectSlotsByName(addChRamWidg)

    def retranslateUi(self, addChRamWidg):
        _translate = QtCore.QCoreApplication.translate
        addChRamWidg.setWindowTitle(_translate("addChRamWidg", "Form"))
        self.lbDate.setText(_translate("addChRamWidg", "Дата заказа"))
        self.lbVoltage.setText(_translate("addChRamWidg", "Напряжение питания [Вт]"))
        self.lbProcProizv.setText(_translate("addChRamWidg", "Производитель"))
        self.cbProizv.setItemText(0, _translate("addChRamWidg", "Kingston"))
        self.lbKol.setText(_translate("addChRamWidg", "Количество"))
        self.lbPrice.setText(_translate("addChRamWidg", "Цена [руб.]"))
        self.lbVolume.setText(_translate("addChRamWidg", "Объём комплекта [Гб]"))
        self.lbComplect.setText(_translate("addChRamWidg", "Оперативная память"))
        self.lbLatency.setText(_translate("addChRamWidg", "CAS-латентность (CL)"))
        self.lbProcGaming.setText(_translate("addChRamWidg", "Игровое комплектующее"))
        self.btnSave.setText(_translate("addChRamWidg", "Сохранить"))
        self.btnCancel.setText(_translate("addChRamWidg", "Отмена"))
        self.lbFullName.setText(_translate("addChRamWidg", "Название оперативной памяти"))
        self.cbGaming.setItemText(0, _translate("addChRamWidg", "Да"))
        self.cbGaming.setItemText(1, _translate("addChRamWidg", "Нет"))
        self.lbRamType.setText(_translate("addChRamWidg", "Тип ОЗУ"))
        self.cbRamType.setItemText(0, _translate("addChRamWidg", "DDR5"))
        self.cbRamType.setItemText(1, _translate("addChRamWidg", "DDR4"))
        self.cbRamType.setItemText(2, _translate("addChRamWidg", "DDR3"))
        self.cbRamType.setItemText(3, _translate("addChRamWidg", "DDR3L"))
        self.cbRamType.setItemText(4, _translate("addChRamWidg", "DDR2"))
        self.lbFreq.setText(_translate("addChRamWidg", "Тактовая частота [МГц]"))
        self.cbModule.setItemText(0, _translate("addChRamWidg", "2"))
        self.cbModule.setItemText(1, _translate("addChRamWidg", "4"))
        self.cbModule.setItemText(2, _translate("addChRamWidg", "8"))
        self.cbModule.setItemText(3, _translate("addChRamWidg", "1"))
        self.lbModule.setText(_translate("addChRamWidg", "Количество модулей"))
        self.cbVolume.setItemText(0, _translate("addChRamWidg", "32"))
        self.cbVolume.setItemText(1, _translate("addChRamWidg", "16"))
        self.cbVolume.setItemText(2, _translate("addChRamWidg", "12"))
        self.cbVolume.setItemText(3, _translate("addChRamWidg", "8"))
        self.cbVolume.setItemText(4, _translate("addChRamWidg", "4"))
        self.cbVolume.setItemText(5, _translate("addChRamWidg", "2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addChRamWidg = QtWidgets.QWidget()
    ui = Ui_addChRamWidg()
    ui.setupUi(addChRamWidg)
    addChRamWidg.show()
    sys.exit(app.exec_())
