# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\add\addChDiskWidg.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addChDiskWidg(object):
    def setupUi(self, addChDiskWidg):
        addChDiskWidg.setObjectName("addChDiskWidg")
        addChDiskWidg.resize(877, 599)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\add\\../../images/win_add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addChDiskWidg.setWindowIcon(icon)
        addChDiskWidg.setStyleSheet("QWidget\n"
"{\n"
"    background: rgb(25, 25, 25);\n"
"    color: white;\n"
"}\n"
"")
        self.line_4 = QtWidgets.QFrame(addChDiskWidg)
        self.line_4.setGeometry(QtCore.QRect(20, 520, 841, 20))
        self.line_4.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lbType = QtWidgets.QLabel(addChDiskWidg)
        self.lbType.setGeometry(QtCore.QRect(320, 170, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbType.setFont(font)
        self.lbType.setStyleSheet("border:0px;")
        self.lbType.setObjectName("lbType")
        self.dateEdit = QtWidgets.QDateEdit(addChDiskWidg)
        self.dateEdit.setGeometry(QtCore.QRect(670, 470, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"}\n"
"QDateEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"QDateEdit::drop-down{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"    border: 2px solid rgb(100,0,0)\n"
"}\n"
"\n"
"QDateEdit:on{\n"
"    border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QDateEdit::up-arrow {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar { background-color: rgb(40,40,40); }\n"
"QCalendarWidget QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 70px;\n"
"    height: 25px;\n"
"    color: rgb(220,220,220);\n"
"    font-size: 14px;\n"
"    icon-size: 30px, 30px;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth {\n"
"    background: rgb(45,45,45);\n"
"    border: none;\n"
"    width: 30px;\n"
"    height: 25px;\n"
"    qproperty-icon:  url(\"E:/pcconf/images/left-arrow.png\");\n"
"    icon-size: 20px, 20px;\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"QToolButton#qt_calendar_nextmonth {\n"
"    background: rgb(35,35,35);\n"
"    border: none;\n"
"    width: 30px;\n"
"    height: 25px;\n"
"    qproperty-icon:  url(\"E:/pcconf/images/right-arrow.png\");\n"
"    icon-size: 20px, 20px;\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    width: 100px;\n"
"    left: 10px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    selection-color: rgb(220,0,0);\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox { \n"
"    width: 45px; \n"
"    font-size:14px; \n"
"    color: white; \n"
"    background: transparent;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"QCalendarWidget QSpinBox::up-button { subcontrol-origin: border;  subcontrol-position: top right;  width:15px; height: 15px; border:1px solid rgb(30,30,30); }\n"
"QCalendarWidget QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right;  width:15px;  height: 15px; border:1px solid rgb(30,30,30);}\n"
"QCalendarWidget QSpinBox::up-arrow { border-image: url(\"E:/pcconf/images/up-arrow.png\"); }\n"
"QCalendarWidget QSpinBox::down-arrow { border-image: url(\"E:/pcconf/images/down-arrow.png\");}\n"
" \n"
"/* header row */\n"
"QCalendarWidget QWidget { alternate-background-color: rgb(50, 50, 50);  border-bottom: 1px solid red; }\n"
" \n"
"/* normal days */\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    font-size:12px;  \n"
"    color: rgb(180, 180, 180);  \n"
"    background-color: rgb(15, 15, 15);  \n"
"    selection-background-color: rgb(64, 64, 64); \n"
"    selection-color: rgb(0, 255, 0); \n"
"    selection-border-color: red;\n"
"    height: 30px;\n"
"}\n"
" \n"
"/* days in other months */\n"
"QCalendarWidget QAbstractItemView:disabled { color: rgb(80, 80, 80); }")
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.lbKol = QtWidgets.QLabel(addChDiskWidg)
        self.lbKol.setGeometry(QtCore.QRect(20, 440, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbKol.setFont(font)
        self.lbKol.setStyleSheet("border:0px;")
        self.lbKol.setObjectName("lbKol")
        self.leVolume = QtWidgets.QLineEdit(addChDiskWidg)
        self.leVolume.setGeometry(QtCore.QRect(490, 280, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leVolume.setFont(font)
        self.leVolume.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leVolume.setInputMask("")
        self.leVolume.setObjectName("leVolume")
        self.lbProcProizv = QtWidgets.QLabel(addChDiskWidg)
        self.lbProcProizv.setGeometry(QtCore.QRect(20, 90, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbProcProizv.setFont(font)
        self.lbProcProizv.setStyleSheet("border:0px;")
        self.lbProcProizv.setObjectName("lbProcProizv")
        self.lbVolume = QtWidgets.QLabel(addChDiskWidg)
        self.lbVolume.setGeometry(QtCore.QRect(490, 250, 221, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbVolume.setFont(font)
        self.lbVolume.setStyleSheet("border:0px;")
        self.lbVolume.setObjectName("lbVolume")
        self.cbRpm = QtWidgets.QComboBox(addChDiskWidg)
        self.cbRpm.setGeometry(QtCore.QRect(20, 380, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbRpm.setFont(font)
        self.cbRpm.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbRpm.setEditable(False)
        self.cbRpm.setIconSize(QtCore.QSize(20, 20))
        self.cbRpm.setDuplicatesEnabled(False)
        self.cbRpm.setFrame(False)
        self.cbRpm.setModelColumn(0)
        self.cbRpm.setObjectName("cbRpm")
        self.cbRpm.addItem("")
        self.cbRpm.addItem("")
        self.cbRpm.addItem("")
        self.cbRpm.addItem("")
        self.cbRpm.addItem("")
        self.cbRpm.addItem("")
        self.cbConnect = QtWidgets.QComboBox(addChDiskWidg)
        self.cbConnect.setGeometry(QtCore.QRect(490, 200, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbConnect.setFont(font)
        self.cbConnect.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbConnect.setEditable(False)
        self.cbConnect.setIconSize(QtCore.QSize(20, 20))
        self.cbConnect.setDuplicatesEnabled(False)
        self.cbConnect.setFrame(False)
        self.cbConnect.setModelColumn(0)
        self.cbConnect.setObjectName("cbConnect")
        self.cbConnect.addItem("")
        self.btnCancel = QtWidgets.QPushButton(addChDiskWidg)
        self.btnCancel.setGeometry(QtCore.QRect(440, 550, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setDefault(False)
        self.btnCancel.setFlat(False)
        self.btnCancel.setObjectName("btnCancel")
        self.lbWrite = QtWidgets.QLabel(addChDiskWidg)
        self.lbWrite.setGeometry(QtCore.QRect(20, 250, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbWrite.setFont(font)
        self.lbWrite.setStyleSheet("border:0px;")
        self.lbWrite.setObjectName("lbWrite")
        self.cbProizv = QtWidgets.QComboBox(addChDiskWidg)
        self.cbProizv.setGeometry(QtCore.QRect(20, 120, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbProizv.setFont(font)
        self.cbProizv.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbProizv.setEditable(False)
        self.cbProizv.setIconSize(QtCore.QSize(20, 20))
        self.cbProizv.setDuplicatesEnabled(False)
        self.cbProizv.setFrame(False)
        self.cbProizv.setModelColumn(0)
        self.cbProizv.setObjectName("cbProizv")
        self.cbProizv.addItem("")
        self.leWrite = QtWidgets.QLineEdit(addChDiskWidg)
        self.leWrite.setGeometry(QtCore.QRect(20, 280, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leWrite.setFont(font)
        self.leWrite.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leWrite.setInputMask("")
        self.leWrite.setObjectName("leWrite")
        self.lbConnect = QtWidgets.QLabel(addChDiskWidg)
        self.lbConnect.setGeometry(QtCore.QRect(490, 170, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbConnect.setFont(font)
        self.lbConnect.setStyleSheet("border:0px;")
        self.lbConnect.setObjectName("lbConnect")
        self.lbRpm = QtWidgets.QLabel(addChDiskWidg)
        self.lbRpm.setGeometry(QtCore.QRect(20, 350, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbRpm.setFont(font)
        self.lbRpm.setStyleSheet("border:0px;")
        self.lbRpm.setObjectName("lbRpm")
        self.lbComplect = QtWidgets.QLabel(addChDiskWidg)
        self.lbComplect.setGeometry(QtCore.QRect(640, 40, 221, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        self.lbComplect.setFont(font)
        self.lbComplect.setStyleSheet("border:0px;")
        self.lbComplect.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbComplect.setObjectName("lbComplect")
        self.lbDate = QtWidgets.QLabel(addChDiskWidg)
        self.lbDate.setGeometry(QtCore.QRect(670, 440, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbDate.setFont(font)
        self.lbDate.setStyleSheet("border:0px;")
        self.lbDate.setObjectName("lbDate")
        self.lbPrice = QtWidgets.QLabel(addChDiskWidg)
        self.lbPrice.setGeometry(QtCore.QRect(170, 440, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbPrice.setFont(font)
        self.lbPrice.setStyleSheet("border:0px;")
        self.lbPrice.setObjectName("lbPrice")
        self.lePrice = QtWidgets.QLineEdit(addChDiskWidg)
        self.lePrice.setGeometry(QtCore.QRect(170, 470, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.lePrice.setFont(font)
        self.lePrice.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.lePrice.setInputMask("")
        self.lePrice.setObjectName("lePrice")
        self.btnSave = QtWidgets.QPushButton(addChDiskWidg)
        self.btnSave.setGeometry(QtCore.QRect(250, 550, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-bottom: 1px solid rgb(0, 255, 8);\n"
"}\n"
"")
        self.btnSave.setObjectName("btnSave")
        self.line = QtWidgets.QFrame(addChDiskWidg)
        self.line.setGeometry(QtCore.QRect(20, 70, 841, 20))
        self.line.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbFullName = QtWidgets.QLabel(addChDiskWidg)
        self.lbFullName.setGeometry(QtCore.QRect(20, 170, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbFullName.setFont(font)
        self.lbFullName.setStyleSheet("")
        self.lbFullName.setObjectName("lbFullName")
        self.rectangle = QtWidgets.QFrame(addChDiskWidg)
        self.rectangle.setGeometry(QtCore.QRect(20, 10, 61, 20))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.line_3 = QtWidgets.QFrame(addChDiskWidg)
        self.line_3.setGeometry(QtCore.QRect(20, 430, 841, 20))
        self.line_3.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(addChDiskWidg)
        self.line_2.setGeometry(QtCore.QRect(20, 330, 841, 20))
        self.line_2.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(220, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.leFullName = QtWidgets.QLineEdit(addChDiskWidg)
        self.leFullName.setGeometry(QtCore.QRect(20, 200, 261, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leFullName.setFont(font)
        self.leFullName.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leFullName.setObjectName("leFullName")
        self.leKol = QtWidgets.QLineEdit(addChDiskWidg)
        self.leKol.setGeometry(QtCore.QRect(20, 470, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leKol.setFont(font)
        self.leKol.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leKol.setInputMask("")
        self.leKol.setObjectName("leKol")
        self.cbType = QtWidgets.QComboBox(addChDiskWidg)
        self.cbType.setGeometry(QtCore.QRect(320, 200, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.cbType.setFont(font)
        self.cbType.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    border: 1px solid red;\n"
"    padding-left: 5px;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"border-image: url(\"E:/pcconf/images/down-arrow.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"width: 17px;\n"
"height: 17px;\n"
"margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgb(250, 250, 250);\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(235, 235, 235);\n"
"    selection-background-color: rgb(240, 240, 240);\n"
"    selection-color: rgb(25, 25, 25);\n"
"}\n"
"")
        self.cbType.setEditable(False)
        self.cbType.setIconSize(QtCore.QSize(20, 20))
        self.cbType.setDuplicatesEnabled(False)
        self.cbType.setFrame(False)
        self.cbType.setModelColumn(0)
        self.cbType.setObjectName("cbType")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.leRead = QtWidgets.QLineEdit(addChDiskWidg)
        self.leRead.setGeometry(QtCore.QRect(210, 280, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.leRead.setFont(font)
        self.leRead.setStyleSheet("QLineEdit{\n"
"    padding-left: 5px;\n"
"    border: 1px solid rgb(20,20,20);\n"
"    background-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  rgb(120,120,120);\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid  red;\n"
"}")
        self.leRead.setInputMask("")
        self.leRead.setObjectName("leRead")
        self.lbRead = QtWidgets.QLabel(addChDiskWidg)
        self.lbRead.setGeometry(QtCore.QRect(210, 250, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbRead.setFont(font)
        self.lbRead.setStyleSheet("border:0px;")
        self.lbRead.setObjectName("lbRead")
        self.line_3.raise_()
        self.line_4.raise_()
        self.lbType.raise_()
        self.dateEdit.raise_()
        self.lbKol.raise_()
        self.leVolume.raise_()
        self.lbProcProizv.raise_()
        self.lbVolume.raise_()
        self.cbRpm.raise_()
        self.cbConnect.raise_()
        self.btnCancel.raise_()
        self.lbWrite.raise_()
        self.cbProizv.raise_()
        self.leWrite.raise_()
        self.lbConnect.raise_()
        self.lbRpm.raise_()
        self.lbComplect.raise_()
        self.lbDate.raise_()
        self.lbPrice.raise_()
        self.lePrice.raise_()
        self.btnSave.raise_()
        self.line.raise_()
        self.lbFullName.raise_()
        self.rectangle.raise_()
        self.line_2.raise_()
        self.leFullName.raise_()
        self.leKol.raise_()
        self.cbType.raise_()
        self.leRead.raise_()
        self.lbRead.raise_()

        self.retranslateUi(addChDiskWidg)
        self.btnCancel.clicked.connect(addChDiskWidg.close)
        QtCore.QMetaObject.connectSlotsByName(addChDiskWidg)

    def retranslateUi(self, addChDiskWidg):
        _translate = QtCore.QCoreApplication.translate
        addChDiskWidg.setWindowTitle(_translate("addChDiskWidg", "Form"))
        self.lbType.setText(_translate("addChDiskWidg", "Тип накопителя"))
        self.lbKol.setText(_translate("addChDiskWidg", "Количество"))
        self.lbProcProizv.setText(_translate("addChDiskWidg", "Производитель"))
        self.lbVolume.setText(_translate("addChDiskWidg", "Объём накопителя [Гб]"))
        self.cbRpm.setItemText(0, _translate("addChDiskWidg", "0"))
        self.cbRpm.setItemText(1, _translate("addChDiskWidg", "7200"))
        self.cbRpm.setItemText(2, _translate("addChDiskWidg", "5900"))
        self.cbRpm.setItemText(3, _translate("addChDiskWidg", "5700"))
        self.cbRpm.setItemText(4, _translate("addChDiskWidg", "5640"))
        self.cbRpm.setItemText(5, _translate("addChDiskWidg", "5400"))
        self.cbConnect.setItemText(0, _translate("addChDiskWidg", "SATA"))
        self.btnCancel.setText(_translate("addChDiskWidg", "Отмена"))
        self.lbWrite.setText(_translate("addChDiskWidg", "Скорость записи [Мб]"))
        self.cbProizv.setItemText(0, _translate("addChDiskWidg", "Seagate"))
        self.lbConnect.setText(_translate("addChDiskWidg", "Разъём подключения"))
        self.lbRpm.setText(_translate("addChDiskWidg", "Скорость вращения шпинделя [об/мин]"))
        self.lbComplect.setText(_translate("addChDiskWidg", "Накопитель"))
        self.lbDate.setText(_translate("addChDiskWidg", "Дата заказа"))
        self.lbPrice.setText(_translate("addChDiskWidg", "Цена [руб.]"))
        self.btnSave.setText(_translate("addChDiskWidg", "Сохранить"))
        self.lbFullName.setText(_translate("addChDiskWidg", "Название накопителя"))
        self.cbType.setItemText(0, _translate("addChDiskWidg", "2.5\" SSD"))
        self.cbType.setItemText(1, _translate("addChDiskWidg", "2.5\" HDD"))
        self.cbType.setItemText(2, _translate("addChDiskWidg", "3.5\" HDD"))
        self.lbRead.setText(_translate("addChDiskWidg", "Скорость чтения [Мб]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addChDiskWidg = QtWidgets.QWidget()
    ui = Ui_addChDiskWidg()
    ui.setupUi(addChDiskWidg)
    addChDiskWidg.show()
    sys.exit(app.exec_())
