# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pcconf\ui\acceptOrderWidg.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_acceptOrderWidg(object):
    def setupUi(self, acceptOrderWidg):
        acceptOrderWidg.setObjectName("acceptOrderWidg")
        acceptOrderWidg.resize(858, 869)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\pcconf\\ui\\../images/faq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        acceptOrderWidg.setWindowIcon(icon)
        acceptOrderWidg.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(30,30,30);\n"
"    color: white;\n"
"\n"
"}\n"
"")
        self.line = QtWidgets.QFrame(acceptOrderWidg)
        self.line.setGeometry(QtCore.QRect(20, 90, 821, 20))
        self.line.setStyleSheet("border:0px;\n"
"border-top: 1px solid red;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbComplect = QtWidgets.QLabel(acceptOrderWidg)
        self.lbComplect.setGeometry(QtCore.QRect(40, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        self.lbComplect.setFont(font)
        self.lbComplect.setStyleSheet("border:0px;")
        self.lbComplect.setObjectName("lbComplect")
        self.rectangle = QtWidgets.QFrame(acceptOrderWidg)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.rectangle.setStyleSheet("background-color: rgb(210, 0, 0);\n"
"border: 1px solid rgb(210, 0, 0);")
        self.rectangle.setFrameShape(QtWidgets.QFrame.HLine)
        self.rectangle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rectangle.setObjectName("rectangle")
        self.lbVideo = QtWidgets.QLabel(acceptOrderWidg)
        self.lbVideo.setGeometry(QtCore.QRect(80, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbVideo.setFont(font)
        self.lbVideo.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbVideo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbVideo.setObjectName("lbVideo")
        self.imgVideocard = QtWidgets.QFrame(acceptOrderWidg)
        self.imgVideocard.setGeometry(QtCore.QRect(40, 120, 31, 31))
        self.imgVideocard.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/graphics-card.png\") 0;")
        self.imgVideocard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgVideocard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgVideocard.setObjectName("imgVideocard")
        self.line_2 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_2.setGeometry(QtCore.QRect(20, 170, 821, 20))
        self.line_2.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_3.setGeometry(QtCore.QRect(20, 250, 821, 20))
        self.line_3.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lbProc = QtWidgets.QLabel(acceptOrderWidg)
        self.lbProc.setGeometry(QtCore.QRect(80, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbProc.setFont(font)
        self.lbProc.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbProc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbProc.setObjectName("lbProc")
        self.line_4 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_4.setGeometry(QtCore.QRect(20, 330, 821, 20))
        self.line_4.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lbMother = QtWidgets.QLabel(acceptOrderWidg)
        self.lbMother.setGeometry(QtCore.QRect(80, 280, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbMother.setFont(font)
        self.lbMother.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbMother.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbMother.setObjectName("lbMother")
        self.previewMother = QtWidgets.QLabel(acceptOrderWidg)
        self.previewMother.setGeometry(QtCore.QRect(290, 280, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewMother.setFont(font)
        self.previewMother.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewMother.setText("")
        self.previewMother.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewMother.setObjectName("previewMother")
        self.line_5 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_5.setGeometry(QtCore.QRect(20, 410, 821, 20))
        self.line_5.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.lbCool = QtWidgets.QLabel(acceptOrderWidg)
        self.lbCool.setGeometry(QtCore.QRect(80, 360, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbCool.setFont(font)
        self.lbCool.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbCool.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbCool.setObjectName("lbCool")
        self.line_6 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_6.setGeometry(QtCore.QRect(20, 490, 821, 20))
        self.line_6.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.lbRam = QtWidgets.QLabel(acceptOrderWidg)
        self.lbRam.setGeometry(QtCore.QRect(80, 440, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbRam.setFont(font)
        self.lbRam.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbRam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbRam.setObjectName("lbRam")
        self.line_7 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_7.setGeometry(QtCore.QRect(20, 650, 821, 20))
        self.line_7.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.lbPower = QtWidgets.QLabel(acceptOrderWidg)
        self.lbPower.setGeometry(QtCore.QRect(80, 600, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbPower.setFont(font)
        self.lbPower.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbPower.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbPower.setObjectName("lbPower")
        self.previewCool = QtWidgets.QLabel(acceptOrderWidg)
        self.previewCool.setGeometry(QtCore.QRect(290, 360, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewCool.setFont(font)
        self.previewCool.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewCool.setText("")
        self.previewCool.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewCool.setObjectName("previewCool")
        self.previewRam = QtWidgets.QLabel(acceptOrderWidg)
        self.previewRam.setGeometry(QtCore.QRect(290, 440, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewRam.setFont(font)
        self.previewRam.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewRam.setText("")
        self.previewRam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewRam.setObjectName("previewRam")
        self.previewPower = QtWidgets.QLabel(acceptOrderWidg)
        self.previewPower.setGeometry(QtCore.QRect(290, 600, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewPower.setFont(font)
        self.previewPower.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewPower.setText("")
        self.previewPower.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewPower.setObjectName("previewPower")
        self.previewProc = QtWidgets.QLabel(acceptOrderWidg)
        self.previewProc.setGeometry(QtCore.QRect(290, 200, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewProc.setFont(font)
        self.previewProc.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewProc.setText("")
        self.previewProc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewProc.setObjectName("previewProc")
        self.previewVideo = QtWidgets.QLabel(acceptOrderWidg)
        self.previewVideo.setGeometry(QtCore.QRect(290, 120, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewVideo.setFont(font)
        self.previewVideo.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewVideo.setText("")
        self.previewVideo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewVideo.setObjectName("previewVideo")
        self.previewBody = QtWidgets.QLabel(acceptOrderWidg)
        self.previewBody.setGeometry(QtCore.QRect(290, 680, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewBody.setFont(font)
        self.previewBody.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewBody.setText("")
        self.previewBody.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewBody.setObjectName("previewBody")
        self.line_8 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_8.setGeometry(QtCore.QRect(20, 730, 821, 20))
        self.line_8.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.lbBody = QtWidgets.QLabel(acceptOrderWidg)
        self.lbBody.setGeometry(QtCore.QRect(80, 680, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbBody.setFont(font)
        self.lbBody.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbBody.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbBody.setObjectName("lbBody")
        self.imgCPU = QtWidgets.QFrame(acceptOrderWidg)
        self.imgCPU.setGeometry(QtCore.QRect(40, 200, 31, 31))
        self.imgCPU.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/cpu-tower.png\") 0;")
        self.imgCPU.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgCPU.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgCPU.setObjectName("imgCPU")
        self.imgMotherboard = QtWidgets.QFrame(acceptOrderWidg)
        self.imgMotherboard.setGeometry(QtCore.QRect(40, 280, 31, 31))
        self.imgMotherboard.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/motherboard.png\") 0;")
        self.imgMotherboard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgMotherboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgMotherboard.setObjectName("imgMotherboard")
        self.imgCPUcooling = QtWidgets.QFrame(acceptOrderWidg)
        self.imgCPUcooling.setGeometry(QtCore.QRect(40, 360, 31, 31))
        self.imgCPUcooling.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/cpucooling.png\") 0;")
        self.imgCPUcooling.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgCPUcooling.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgCPUcooling.setObjectName("imgCPUcooling")
        self.imgRam = QtWidgets.QFrame(acceptOrderWidg)
        self.imgRam.setGeometry(QtCore.QRect(40, 440, 31, 31))
        self.imgRam.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/ram (1).png\") 0;")
        self.imgRam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgRam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgRam.setObjectName("imgRam")
        self.imgDisk = QtWidgets.QFrame(acceptOrderWidg)
        self.imgDisk.setGeometry(QtCore.QRect(40, 520, 31, 31))
        self.imgDisk.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/hard-drive.png\") 0;")
        self.imgDisk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgDisk.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgDisk.setObjectName("imgDisk")
        self.previewDisk = QtWidgets.QLabel(acceptOrderWidg)
        self.previewDisk.setGeometry(QtCore.QRect(290, 520, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.previewDisk.setFont(font)
        self.previewDisk.setStyleSheet("color: rgb(235,235,235);\n"
"border: 0px;\n"
"")
        self.previewDisk.setText("")
        self.previewDisk.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.previewDisk.setObjectName("previewDisk")
        self.line_9 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_9.setGeometry(QtCore.QRect(20, 570, 821, 20))
        self.line_9.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.lbDisk = QtWidgets.QLabel(acceptOrderWidg)
        self.lbDisk.setGeometry(QtCore.QRect(80, 520, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbDisk.setFont(font)
        self.lbDisk.setStyleSheet("color: rgb(200,200,200);\n"
"border: 0px;\n"
"")
        self.lbDisk.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbDisk.setObjectName("lbDisk")
        self.imgBody = QtWidgets.QFrame(acceptOrderWidg)
        self.imgBody.setGeometry(QtCore.QRect(40, 680, 31, 31))
        self.imgBody.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/case.png\") 0;")
        self.imgBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgBody.setObjectName("imgBody")
        self.imgPower = QtWidgets.QFrame(acceptOrderWidg)
        self.imgPower.setGeometry(QtCore.QRect(40, 600, 31, 31))
        self.imgPower.setStyleSheet("border: 0px;\n"
"border-image: url(\"E:/pcconf/images/power.png\") 0;")
        self.imgPower.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgPower.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgPower.setObjectName("imgPower")
        self.btnAcceptPurcashe = QtWidgets.QPushButton(acceptOrderWidg)
        self.btnAcceptPurcashe.setGeometry(QtCore.QRect(260, 810, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnAcceptPurcashe.setFont(font)
        self.btnAcceptPurcashe.setStyleSheet("\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color: white;\n"
"background: #bf0000;\n"
"}\n"
"\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: #FF0000;\n"
"color: white;\n"
"border: 1px solid #bf0000;\n"
"}")
        self.btnAcceptPurcashe.setObjectName("btnAcceptPurcashe")
        self.btnClose = QtWidgets.QPushButton(acceptOrderWidg)
        self.btnClose.setGeometry(QtCore.QRect(440, 810, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    border:1px solid rgb(70,70,70);\n"
"    background-color: rgb(35,35,35);\n"
"    color: #fffafa;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    border:1px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-color: rgb(40,40,40);\n"
"    border-bottom: 1px solid  red;\n"
"    color: red;\n"
"}\n"
"")
        self.btnClose.setObjectName("btnClose")
        self.lb_price = QtWidgets.QLabel(acceptOrderWidg)
        self.lb_price.setGeometry(QtCore.QRect(400, 760, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setKerning(True)
        self.lb_price.setFont(font)
        self.lb_price.setStyleSheet("QLabel{\n"
"border: 0px;\n"
"\n"
"}")
        self.lb_price.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_price.setObjectName("lb_price")
        self.lb_price_3 = QtWidgets.QLabel(acceptOrderWidg)
        self.lb_price_3.setGeometry(QtCore.QRect(480, 760, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setKerning(True)
        self.lb_price_3.setFont(font)
        self.lb_price_3.setStyleSheet("QLabel{\n"
"border: 0px;\n"
"\n"
"}")
        self.lb_price_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_price_3.setObjectName("lb_price_3")
        self.lb_price_2 = QtWidgets.QLabel(acceptOrderWidg)
        self.lb_price_2.setGeometry(QtCore.QRect(340, 760, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setKerning(True)
        self.lb_price_2.setFont(font)
        self.lb_price_2.setStyleSheet("QLabel{\n"
"border: 0px;\n"
"\n"
"}")
        self.lb_price_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_price_2.setObjectName("lb_price_2")
        self.line_10 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_10.setGeometry(QtCore.QRect(250, 110, 20, 61))
        self.line_10.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_11.setGeometry(QtCore.QRect(250, 170, 20, 81))
        self.line_11.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_12.setGeometry(QtCore.QRect(250, 250, 20, 81))
        self.line_12.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_13.setGeometry(QtCore.QRect(250, 330, 20, 81))
        self.line_13.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_14.setGeometry(QtCore.QRect(250, 410, 20, 81))
        self.line_14.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_15.setGeometry(QtCore.QRect(250, 490, 20, 81))
        self.line_15.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_16.setGeometry(QtCore.QRect(250, 570, 20, 81))
        self.line_16.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_17.setGeometry(QtCore.QRect(250, 650, 20, 81))
        self.line_17.setStyleSheet("border:0px;\n"
"border-right: 1px solid rgb(100,100,100);\n"
"border-bottom: 1px solid rgb(100,100,100);\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.lbDate = QtWidgets.QLabel(acceptOrderWidg)
        self.lbDate.setGeometry(QtCore.QRect(520, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lbDate.setFont(font)
        self.lbDate.setStyleSheet("border:0px;")
        self.lbDate.setObjectName("lbDate")
        self.dateEdit = QtWidgets.QDateEdit(acceptOrderWidg)
        self.dateEdit.setGeometry(QtCore.QRect(720, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px;\n"
"    border-bottom: 1px solid rgb(120,120,120);\n"
"    padding-left: 5px;\n"
"}\n"
"QDateEdit:hover{\n"
"    background-color: rgb(55,55,55);\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"QDateEdit::drop-down{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    border-image: url(\"E:/pcconf/images/down-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"    border: 2px solid rgb(100,0,0)\n"
"}\n"
"\n"
"QDateEdit:on{\n"
"    border: 2px solid rgb(100,0,0);\n"
"}\n"
"\n"
"QDateEdit::up-arrow {\n"
"    border-image: url(\"E:/pcconf/images/up-arrow-gray.png\");\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar { background-color: rgb(40,40,40); }\n"
"QCalendarWidget QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 70px;\n"
"    height: 25px;\n"
"    color: rgb(220,220,220);\n"
"    font-size: 14px;\n"
"    icon-size: 30px, 30px;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth {\n"
"    background: rgb(45,45,45);\n"
"    border: none;\n"
"    width: 30px;\n"
"    height: 25px;\n"
"    qproperty-icon:  url(\"E:/pcconf/images/left-arrow.png\");\n"
"    icon-size: 20px, 20px;\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"QToolButton#qt_calendar_nextmonth {\n"
"    background: rgb(35,35,35);\n"
"    border: none;\n"
"    width: 30px;\n"
"    height: 25px;\n"
"    qproperty-icon:  url(\"E:/pcconf/images/right-arrow.png\");\n"
"    icon-size: 20px, 20px;\n"
"    border-bottom: 1px solid red;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    width: 100px;\n"
"    left: 10px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    selection-color: rgb(220,0,0);\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox { \n"
"    width: 45px; \n"
"    font-size:14px; \n"
"    color: white; \n"
"    background: transparent;\n"
"    selection-background-color: rgb(105, 0, 0);\n"
"    selection-color: rgb(255, 255, 255);\n"
"}\n"
"QCalendarWidget QSpinBox::up-button { subcontrol-origin: border;  subcontrol-position: top right;  width:15px; height: 15px; border:1px solid rgb(30,30,30); }\n"
"QCalendarWidget QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right;  width:15px;  height: 15px; border:1px solid rgb(30,30,30);}\n"
"QCalendarWidget QSpinBox::up-arrow { border-image: url(\"E:/pcconf/images/up-arrow.png\"); }\n"
"QCalendarWidget QSpinBox::down-arrow { border-image: url(\"E:/pcconf/images/down-arrow.png\");}\n"
" \n"
"/* header row */\n"
"QCalendarWidget QWidget { alternate-background-color: rgb(50, 50, 50);  border-bottom: 1px solid red; }\n"
" \n"
"/* normal days */\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    font-size:12px;  \n"
"    color: rgb(180, 180, 180);  \n"
"    background-color: rgb(15, 15, 15);  \n"
"    selection-background-color: rgb(64, 64, 64); \n"
"    selection-color: rgb(0, 255, 0); \n"
"    selection-border-color: red;\n"
"    height: 30px;\n"
"}\n"
" \n"
"/* days in other months */\n"
"QCalendarWidget QAbstractItemView:disabled { color: rgb(80, 80, 80); }")
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.line_18 = QtWidgets.QFrame(acceptOrderWidg)
        self.line_18.setGeometry(QtCore.QRect(340, 790, 161, 20))
        self.line_18.setStyleSheet("border:0px;\n"
"border-top: 1px solid rgb(100,100,100);")
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line.raise_()
        self.lbComplect.raise_()
        self.rectangle.raise_()
        self.lbVideo.raise_()
        self.imgVideocard.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.lbProc.raise_()
        self.line_4.raise_()
        self.lbMother.raise_()
        self.previewMother.raise_()
        self.line_5.raise_()
        self.lbCool.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.lbPower.raise_()
        self.previewCool.raise_()
        self.previewRam.raise_()
        self.previewPower.raise_()
        self.previewProc.raise_()
        self.previewVideo.raise_()
        self.previewBody.raise_()
        self.line_8.raise_()
        self.lbBody.raise_()
        self.imgCPU.raise_()
        self.imgMotherboard.raise_()
        self.imgCPUcooling.raise_()
        self.imgRam.raise_()
        self.imgDisk.raise_()
        self.previewDisk.raise_()
        self.line_9.raise_()
        self.lbDisk.raise_()
        self.imgBody.raise_()
        self.imgPower.raise_()
        self.btnAcceptPurcashe.raise_()
        self.btnClose.raise_()
        self.lb_price.raise_()
        self.lb_price_3.raise_()
        self.lb_price_2.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.lbRam.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.line_17.raise_()
        self.lbDate.raise_()
        self.dateEdit.raise_()
        self.line_18.raise_()

        self.retranslateUi(acceptOrderWidg)
        self.btnClose.clicked.connect(acceptOrderWidg.close)
        QtCore.QMetaObject.connectSlotsByName(acceptOrderWidg)

    def retranslateUi(self, acceptOrderWidg):
        _translate = QtCore.QCoreApplication.translate
        acceptOrderWidg.setWindowTitle(_translate("acceptOrderWidg", "Подтверждение заказа"))
        self.lbComplect.setText(_translate("acceptOrderWidg", "Комплектующие"))
        self.lbVideo.setText(_translate("acceptOrderWidg", "ВИДЕОКАРТА"))
        self.lbProc.setText(_translate("acceptOrderWidg", "ПРОЦЕССОР"))
        self.lbMother.setText(_translate("acceptOrderWidg", "МАТЕРИНСКАЯ ПЛАТА"))
        self.lbCool.setText(_translate("acceptOrderWidg", "ОХЛАЖДЕНИЕ"))
        self.lbRam.setText(_translate("acceptOrderWidg", "ОПЕРАТИВНАЯ ПАМЯТЬ"))
        self.lbPower.setText(_translate("acceptOrderWidg", "БЛОК ПИТАНИЯ"))
        self.lbBody.setText(_translate("acceptOrderWidg", "КОРПУС"))
        self.lbDisk.setText(_translate("acceptOrderWidg", "НАКОПИТЕЛЬ"))
        self.btnAcceptPurcashe.setText(_translate("acceptOrderWidg", "Подтвердить"))
        self.btnClose.setText(_translate("acceptOrderWidg", "Отмена"))
        self.lb_price.setText(_translate("acceptOrderWidg", "000 000"))
        self.lb_price_3.setText(_translate("acceptOrderWidg", " ₽"))
        self.lb_price_2.setText(_translate("acceptOrderWidg", "Цена:"))
        self.lbDate.setText(_translate("acceptOrderWidg", "Дата совершения заказа:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    acceptOrderWidg = QtWidgets.QWidget()
    ui = Ui_acceptOrderWidg()
    ui.setupUi(acceptOrderWidg)
    acceptOrderWidg.show()
    sys.exit(app.exec_())
